### ISSUE TITLE
`The procedure entry point EXTPTR_PROT could not be located in the dynamic link library C:\User\lidan\R\library\rlang\libs\x64\rlang.dll`

### ISSUE THREAD

**Issue by danli349** [hadley/r-pkgs#1009]
Hello

When I run `R CMD check regexcite_0.0.0.9000.tar.gz` in windows terminal following the page "https://r-pkgs.org/workflow101.html"
I got this error:

![image](https://github.com/hadley/r-pkgs/assets/33963919/681c665b-e580-4363-ba6f-5ad1361f33b7)

I reinstalled `rlang` package, but this error still exists.

When I run `check()` in `R` console, everything is correct.

Can you help to let me know what the reason for this error?

Thanks

**Comment by jennybc** [comment]
This smells like you're using a version of rlang installed for one version of R with a _different_ version of R. I can't say how you are getting into this situation, but can you think of anything creative or exciting you have done around R versions? Keep in mind, when you update R from, say 4.2.something to 4.3.something, you MUST reinstall all of your packages.

In any case, this isn't a question for the R Packages book. You might want to follow up on the community site if you can't get unstuck: https://community.rstudio.com/
