### ISSUE TITLE
"Register as an Apple developer" gives a page not found error

### ISSUE THREAD

**Issue by jacobpstein** [hadley/r-pkgs#1023]
In System Set-Up section 2.3.2 (https://r-pkgs.org/setup.html#macos), the link to register as an Apple developer doesn't work. I believe the new link is here: https://developer.apple.com/programs/enroll/

Thanks!

**Comment by jennybc** [comment]
Would you like to make a pull request with the proposed change?

**Comment by jacobpstein** [comment]
Certainly. Incoming! Thanks for the quick response.
