### ISSUE TITLE
Author triple dash in reference list

### ISSUE THREAD

**Issue by arebruvold** [hadley/r-pkgs#1077]
[Reference list](https://r-pkgs.org/references.html) shows ––– instead of author, despite reference being correct. I tried to fix this in commit [c5e8811](https://github.com/hadley/r-pkgs/commit/c5e881132d717b28e8801c6e1f38c8890f4ffd47), but this apparently did not fix it.

EDIT: This appears to be related to the citation style. Intended behavior?

**Comment by jennybc** [comment]
I think it must mean "same author list as previous listing"?

**Comment by arebruvold** [comment]
That is likely the case, although I have never seen this "in the wild". I close the issue as it not related to this repo.
