### ISSUE TITLE
is there a group/forum to ask questions

### ISSUE THREAD

**Issue by xvtstephen** [hadley/r-pkgs#1081]
Hello,

certain things do not turn out as expected, but that is normal. is there a group or a forum where I can ask questions?

**Comment by maelle** [comment]
https://forum.posit.co/c/package-development/11

**Comment by jonthegeek** [comment]
We'd also love to help at DSLC.io! We've had 6 book club cohorts so far for this book. You can watch our meeting videos at [DSLC.video](https://DSLC.video). The most recent cohort is [here](https://www.youtube.com/playlist?list=PL3x6DOfs2NGjSSjJdHz4uqeAxqiuBSEaz).

**Comment by jennybc** [comment]
Thanks @maelle and @jonthegeek for pointing out some good places to discuss things (that might then turn into issues).
