### ISSUE TITLE
`library(testthat)` and `local_edition(3)` are called out in "Important!" boxes, but should probably be hidden

### ISSUE THREAD

**Issue by Kodiologist** [hadley/r-pkgs#1088]
For example, `testing-design.Rmd` starts with "Your test files should not include these `library()` calls." I think you should just use `echo = FALSE` instead.

**Comment by jennybc** [comment]
This is displayed as intended. If a user wants to execute the code in this chapter and follow along, they have to execute this code. It's maddening to encounter code in a blog post or tutorial that omits the key set up steps to make the code actually run. However, it is important to know that these bits are necessary for interactive exploration, but will be accomplished differently in the context of a package.

**Comment by Kodiologist** [comment]
Okay. I thought the intention was that if a reader actually tried any of this code, they would do it in a package. I'm used to pytest where there's no real support for running tests in the REPL.

**Comment by jennybc** [comment]
Yea, the code works outside of a package and is being executed "live" to render the book (and can be executed in a REPL). We just want to make it clear that those two commands are part of the interactive experimentation and not indicative of how you rig things in a package.
