### ISSUE TITLE
Git/GitHub page: Benefits of GitHub section: mention rendering of csv/tsv

### ISSUE THREAD

**Issue by daattali** [hadley/r-pkgs#179]
In the [Git page under Benefits of using GitHub](http://r-pkgs.had.co.nz/git.html#github-benefit), the first bullet point talks about how nicely `R`, `Rmd`, `md`, and especially `README.md` files are rendered.  It might be worth to add that csv/tsv files get rendered in a very helpful way as well; I often use github to view a tabular dataset.

**Comment by jennybc** [comment]
I think this chapter will get leaner and link out to Happy Git, which already covers this: http://happygitwithr.com/repo-browsability.html#delimited-files
