### ISSUE TITLE
Import advice generates unfortunate NOTE in R CMD check

### ISSUE THREAD

**Issue by vspinu** [hadley/r-pkgs#203]
From [namespace/import-r](https://github.com/hadley/r-pkgs/blob/master/namespace.rmd#r-functions-import-r):

> If you are using just a few functions from another package, my recommendation is to note the package name in the Imports: field of the DESCRIPTION file and call the function(s) explicitly using ::, e.g., pkg::fun().

This generates CMD check note `Namespace in Imports field not imported from ...`. For example in the current lubridate: 

```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘memoise’
  All declared Imports should be used.
```

To silence this note one would need to use `@importFrom pkg func` at least once in the package.

**Comment by hadley** [comment]
That's because you've created a build-time dependency not a run time dependency. (Use it in a function to see why)

I'm not sure what the best solution is. This action is fundmentally dangerous because it uses the memorise package that you have installed when running R CMD build, not the package loaded when the user loads your package

**Comment by vspinu** [comment]
> That's because you've created a build-time dependency not a run time dependency.

Yeh. That's indeed the reason for it. Thanks.

> I'm not sure what the best solution is. 

I can think of two solutions. Either to use an unlocked environment inside the package to hold the function or implement a simple caching mechanism inside this function and abandon memoise dependency.. As memoise is used only once in the package I will probably go with the second.


------
Any ideas about where the other NOTE comes from?

```
* checking dependencies in R code ... NOTE
Package in Depends field not imported from: ‘methods’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
```
I don't see the point of this message;`methods` is always attached. 

It seems to be a common issue with `methods` which some people  [fix](https://code.google.com/p/pbs-modelling/issues/detail?id=95) by importing the whole method package. An outrageous solution as all exported functions from `methods` are effectively copied into each of such packages.

**Comment by hadley** [comment]
Methods is not attached when you use Rscript (ridiculous but true). Importing the whole package is fine (if a bit inelegant) - the copies are just pointers, not deep. You can just important individual methods of you want to avoid that.

**Comment by vspinu** [comment]
> Methods is not attached when you use Rscript (ridiculous but true).

Aha!

> Importing the whole package is fine (if a bit inelegant) - the copies are just pointers, not deep. You can just important individual methods of you want to avoid that. 

Yeh. I did the latter. Thanks.
