### ISSUE TITLE
Check pre-reqs for RStudio support for devtools::document()

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#218]
When you say things like

> Run `devtools::document(`) (or press Cmd + Shift + D in RStudio) to convert roxygen comments to .Rd files.

taken from here: http://r-pkgs.had.co.nz/man.html#man-workflow … you might want to check this will work on a fresh, default RStudio installation.

FWIW I needed to check "Generate documentation with Roxygen" in Build Tools section of the Project options, then work through the configuration options to get this keyboard shortcut and the Build > Document menu item. But it's possible my situation has to do w/ previous usage or settings?

**Comment by hadley** [comment]
Yeah, it depends on when and how you created the package :/

**Comment by hadley** [comment]
This just needs a small caveat (and check with @kevinushey that this is still true), but creating a package-project using RStudio does not automatically turn roxygen2 on (so you'll need to do it yourself).

(This is sidebar material at most)

**Comment by kevinushey** [comment]
Right, we still don't activate roxygen2 by default in package projects.

We do try to initialize values in the `DESCRIPTION` based on the values within the `devtools.desc` option, although I don't think we actually document this behavior anywhere. Maybe we should also turn on `roxygen2` support if we detect that the user has already bought into the `devtools` ecosystem?

**Comment by ValeriVoev** [comment]
As per @kevinushey 's response in RStudio Community (https://community.rstudio.com/t/build-package-documentation-shortcut-not-working/36201):

> You may need to explicitly check that you've enabled documentation building with devtools. Check within Tools -> Project Options... -> Build Tools; there should be a checkbox:
> 
>  Generate documentation with Roxygen
> 
> Is that preference checked?


I think that this brief explanation should be included in the section on object documentation.

**Comment by hadley** [comment]
I think we can now close this since it no longer seems to be causing issues when teaching, perhaps due to increased use of `usethis::create_package()`
