### ISSUE TITLE
Describe how to document an entire package via roxygen

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#219]
I feel like I've read something you've written about this before but cannot find in current draft of book or elsewhere by you. But here's the info I mean from a page of a book by Richard Cotton:

https://books.google.ca/books?id=7dyzAAAAQBAJ&pg=PA319&lpg=PA319#v=onepage&q&f=false

Is this in the book anywhere at this point?

**Comment by hadley** [comment]
It was, but it seems to have gone missing :(

**Comment by hadley** [comment]
I'll add it back in tomorrow
