### ISSUE TITLE
Should add info about unloading DLLs in .onUnload

### ISSUE THREAD

**Issue by wch** [hadley/r-pkgs#22]
See: 
http://r.789695.n4.nabble.com/Using-onUnload-to-unload-DLLs-td4637562.html

It looks like this might cause some problems when used with devtools, though, because of the package path. However, if you don't do this, then when a package is unloaded with `unloadNamespace`, the DLL stays loaded.

**Comment by jhrcook** [comment]
I have a quick related question: Where do I add the function `.onUnload()`?

**Comment by hadley** [comment]
It doesn't matter, but it's conventional to put it in `zzz.R`.

**Comment by jennybc** [comment]
As a general technique, you can get lots of examples in front of your eyeballs with a GitHub search.

Here's one that shows ~1K `.onLoad()` definitions across all of CRAN:

https://github.com/search?q=.onLoad+user%3Acran+path%3AR&type=Code

**Comment by jhrcook** [comment]
@hadley Thank you for replying to a comment on a closed issue 🙂

@jennybc Thanks for pointing that out! It’s definitely a tool I need to use more readily and learn to use the keywords.
