### ISSUE TITLE
Missing context: "Make sure to add rJava to Imports."

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/r-pkgs#223]
The ending sentence "Make sure to add rJava to Imports." in https://github.com/hadley/r-pkgs/blob/master/inst.rmd needs more background / context / cross references.  It assumes/implies that everyone uses the rJava package, which may not be true.  Some simply do launch Java class/jar via a `system()` call to `java` or other Java interpreters (I pass mine onto Matlab).

**Comment by hadley** [comment]
I think we should simply remove this sentence since we don't want to get into how you should connect R and java

**Comment by hadley** [comment]
See we don't maintain any packages that use rJava (or java in any way, shape, or form), I think it's better for us to stay out of this.
