### ISSUE TITLE
Contraction: Source comment example contradicts guide

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/r-pkgs#224]
The source code comment examples used following passage [https://github.com/hadley/r-pkgs/blob/master/r.rmd] contradicts the "Comments should explain the why, not the what.":

---
### Commenting guidelines

Comment your code. Each line of a comment should begin with the comment symbol and a single space: `#`. Comments should explain the why, not the what. \index{comments}

Use commented lines of `-` and `=` to break up your file into easily readable chunks.

``` r, eval = FALSE
# Load data ---------------------------

# Plot data ---------------------------
```

---

**Comment by hadley** [comment]
I'd say those comments fall under the use comments for chucking category.

**Comment by HenrikBengtsson** [comment]
Yes, I understand, but a first timer reading "Comments should explain the why, not the what" would look for an example, and then see something that uses "the what".

**Comment by hadley** [comment]
This entire section will be revisited now that http://style.tidyverse.org exists
