### ISSUE TITLE
typo change: Git and Github page

### ISSUE THREAD

**Issue by CDCookJr** [hadley/r-pkgs#254]
On the <b>Git and Github</b> page, "Record Changes" paragraph, the following text is written:
<b>"Using a Git commit is like using an anchors and other protection when climbing."</b>.
Suggested revision:
<b> "using anchors and ..."</b>

Or alternatively:
<b> "using an anchor" and...</b>

"I assign the copyright of this contribution to Hadley Wickham".

**Comment by CDCookJr** [comment]
And thanks for the great work with R!!

**Comment by jennybc** [comment]
Wording seems to have been smoothed out since then.
