### ISSUE TITLE
Comments on Comments

### ISSUE THREAD

**Issue by Ironholds** [hadley/r-pkgs#267]
The section on [roxygen](https://github.com/hadley/r-pkgs/blob/master/man.rmd#roxygen-comments-roxygen-comments) says:

> Each block includes some text before the first tag. This is called the introduction, and is parsed specially:

Does this not introduce the potential for confusion as to why none of my packages have text before the first tag, which is <code>@title</code>? ;p. That is, it's possibly to write valid roxygen syntax that includes that text after tags, as well as valid roxygen with no tags for that text.

**Comment by hadley** [comment]
You can, but I don't think you should

**Comment by Ironholds** [comment]
Whyso?

**Comment by hadley** [comment]
No real reason, but that's the style I've adopted, so best to be consistent

**Comment by Ironholds** [comment]
Totally; I'm not saying "everyone should use this style" - I'm saying that it's possible to explicitly tag title and description too, and so if they dig into some roxygenised packages they'll not see "text before the first tag"; it'd be good for the documentation section to note that. Would it be easier for me to just submit a proposed patch?

**Comment by hadley** [comment]
Hmmmmm, maybe in a sidebar? (which I have no way to represent in pandoc :/)

**Comment by Ironholds** [comment]
Hrm. Does Pandoc have footnotes? Maybe one o'those.

**Comment by hadley** [comment]
Yes, good idea!

**Comment by Ironholds** [comment]
Now fixed!
