### ISSUE TITLE
Show how to link to documentation in other packages

### ISSUE THREAD

**Issue by holstius** [hadley/r-pkgs#273]
One might write a package "bar" that depends on a previous package ("foo"), and wish to link to vignette "abc" in package "foo" from a vignette in the new package. 

Or one might wish to link to a vignette in someone else's package (taking the risk that the link could break).

A cursory Google search didn't seem to turn up any examples of this ... ? In RStudio, the following naïve attempt:

```

---
title: "A Vignette in Package Bar"
----

Have a look at this [Other Vignette](`r system.file("doc", "abc.html", package="foo")`)
```

... failed; the URL for the link (as rendered in the Preview Pane) was `http://127.0.0.1:28617/Library/Frameworks/R.framework/Versions/3.1/Resources/library/foo/doc/abc.html` (which yields a "not found").

**Comment by hadley** [comment]
I don't think it's currently possible. I recommend people run (e.g.) `vignette("abc", package = "foo")` or link to the vignette on CRAN

**Comment by holstius** [comment]
Ah. Well, thanks regardless!

**Comment by hadley** [comment]
Still no better, although we'll need to discuss this in the pkgdown chapter (which does not yet exist)
