### ISSUE TITLE
Update testing section to use native R support in travis

### ISSUE THREAD

**Issue by craigcitro** [hadley/r-pkgs#276]
I'm planning on handling this shortly, but it's never bad to have an issue to track. :wink: 

cc @hadley

**Comment by vnijs** [comment]
Ah. I submitted a pull-request for this section to try and help out (#280) before I notice this issue. I assume you (@craigcitro) will do a much better job :) And thanks for making it so easy to use Travis with R!

**Comment by jennybc** [comment]
Folding this in to #355. Thanks.
