### ISSUE TITLE
"Documenting datasets" is out of sync?

### ISSUE THREAD

**Issue by gonike** [hadley/r-pkgs#282]
It seems to me that the section "Documenting datasets" is quite largely out of sync with the actual code being used in the documentation of the diamonds dataset in the ggplot2 package. I do not know whether this is intential, but it can be confusing.

Moreover, a short note on _where_ to place this documentation block (in the ggplot2.r file) would be nice. At least I was wondering where I should put that.

(I assign the copyright of this contribution to Hadley Wickham.)

**Comment by jennybc** [comment]
This seems to be resolve now.
