### ISSUE TITLE
Minor typos in figure captions in Kobo reader version

### ISSUE THREAD

**Issue by TonyLadson** [hadley/r-pkgs#285]
Caption to Figure 13-6 "...changed in the seclted [selected] file"  
Caption to Figure 13-8 "...all the commits in your at top.."?  Perhaps "...all the commits in your file at the top..."

I assign the copyright of this contribution to Hadley Wickham

**Comment by hadley** [comment]
Due to complicated reasons there are no captions in the version of the book that we have.
