### ISSUE TITLE
p. 82 Search Path discussion missing "not" in discussion of loading vs attaching...

### ISSUE THREAD

**Issue by gtog** [hadley/r-pkgs#287]
I think you are missing the word "not" in the following sentence(s):

"After loading, the package is available in memory, but it's on the search path. That means you can't access its components without using ::."

I think that should say, "...but it's _not_ on the search path. That means..."

Apologies if I am mistaken. 

-adam

**Comment by rodrigomurta** [comment]
I agree. Small typo.

**Comment by jennybc** [comment]
Seems to be fixed now.
