### ISSUE TITLE
Markdown ordered lists guidance

### ISSUE THREAD

**Issue by scw** [hadley/r-pkgs#288]
The guidance for Markdown [ordered lists](https://github.com/hadley/r-pkgs/blob/master/vignettes.rmd#lists)  caught me for a loop. It recommends a syntax of leaving all numbered list elements the same:

```
1. Item 1
1. Item 2
1. Items are numbered automatically, even though they all start with 1.
```

While this is perfectly valid Markdown, I think it confuses rather than clarifies. Any numbers will be parsed the same way, and insertion of random numbers into the list doesn't affect its rendering. It'd be better to be consistent with the other resources showing ordered lists in a simple ascending fashion, as that leads to clearer raw text, and in most cases leads to a consistency of referencing between the raw and rendered versions. That the numbers are arbitrary is perhaps worth mentioning as an aside.

A few other presentations of ordered lists:
- [Pandoc](http://pandoc.org/README.html#ordered-lists)
- [Daring Fireball](http://daringfireball.net/projects/markdown/syntax#list)
- [Github](https://help.github.com/articles/markdown-basics/)
- [RMarkdown](http://rmarkdown.rstudio.com/authoring_basics.html)

Happy to make a pull request, but figured an issue was in order first since this is in effect a nit.

"I assign the copyright of this contribution to Hadley Wickham".

**Comment by hadley** [comment]
Since the book was written, the knowledge of markdown in the R community has improved substantially. The next edition of the book will just point to guides elsewhere
