### ISSUE TITLE
@param x,y Description: Not parseable

### ISSUE THREAD

**Issue by zeehio** [hadley/r-pkgs#291]
The syntax `@param x,y Description` suggested in http://r-pkgs.had.co.nz/man.html#man-functions is as far as I know not documented in Doxygen/roxygen.

This is a problem for instance when using tidyr with Rstudio, where the contextual help does not show for some arguments of the `tidyr::spread` function:

![image](https://cloud.githubusercontent.com/assets/75441/7514536/7d72dcda-f4be-11e4-9b41-92d950d871a9.png)

For other arguments the description is well given:

![image](https://cloud.githubusercontent.com/assets/75441/7514546/9aa6cf5a-f4be-11e4-8776-59ccbea9149f.png)

I think it would be good to either try to document the `@param x,y Description` behaviour in roxygen/doxygen and push to fix the RStudio contextual help issue, or to refrain from using it.

This is a very minor issue, I may be able to help fixing it but I would like feedback on your opinion on which way we should move to.

In case you need it, I assign any copyright of this contribution to Hadley Wickham.

**Comment by hadley** [comment]
@kevinushey looks like rstudio doc parser needs to understand compound argument documentation

@zeehio it's more of an Rd feature than a roxygen2 feature

**Comment by kevinushey** [comment]
This should already work in the preview.

**Comment by zeehio** [comment]
Thank you for your kind and quick reply.

This topic fell a bit in the middle of several areas (documentation, Rd, rstudio...) and I did not know where to look at. I will try to dig further in the future. 

My sincere apologies if I wasted your time.

Have a nice day and thank you very much for your great work.
