### ISSUE TITLE
Individual chapters no longer show up in left sidebar of index page

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#314]
It feels like "Contents" used to have links to the individual chapters below it, no? I now see there's a drop-down menu available in upper right corner but I had gotten used to using the left sidebar to access chapters.

<img width="627" alt="r-packages-contents" src="https://cloud.githubusercontent.com/assets/599454/8809146/8cc1cc7e-2f9b-11e5-8fa0-0fac5c2ce1d7.png">

**Comment by dracodoc** [comment]
@hadley , I'll also suggest to place a table of contents in left side, and better to have a next/previous button on page bottom. 

Right now the left side only have the sub contents for current page. User need to click the drop down menu to find next chapter. And it's not obvious which chapter are you currently in.

**Comment by jennybc** [comment]
This will migrate to current bookdown soon.
