### ISSUE TITLE
Add richer license discussion

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#32]
- Clarify use of LICENSE, LICENSE.note, COPYING, COPYING.lib, AUTHORS, COPYRIGHTS and NOTICE
- Describe which go in package dir and which in `inst/`
- More information about the GPL and how it plays with packages that link to R

**Comment by hadley** [comment]
Update to mention how `use_mit_license()` etc work (i.e. including `LICENSE.md` that's build-ignored)

**Comment by jennybc** [comment]
Material cut out of Whole Game that should be reincorporated in the main license section

For the record, Whole Game *does* explain the "deal" with `LICENSE.md`, since it uses MIT and it comes up.
---

For future projects, there is more guidance on licenses in these sources:

  * The [License section of this book](#license)
  * [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing)
  * GitHub's guide at <http://choosealicense.com>

**Comment by miguelmorin** [comment]
When a project starts with MIT, with a `LICENSE` file with copyright holder and year, then switches to GPL because it starts including GPL packages, does it need to delete the `LICENSE` file? Either way, I suggest clarifying that in the book.

**Comment by wch** [comment]
I think R-exts now sort of suggests that one can include a normal LICENSE file (that is, normal with respect to the open source world), and add it to .Rbuildignore. More complicated stuff goes into LICENSE.note.

> Whereas you should feel free to include a license file in your source distribution, please do not arrange to install yet another copy of the GNU COPYING or COPYING.LIB files but refer to the copies on https://www.R-project.org/Licenses/ and included in the R distribution (in directory share/licenses). Since files named LICENSE or LICENCE will be installed, do not use these names for standard license files. To include comments about the licensing rather than the body of a license, use a file named something like LICENSE.note.


At least, that's what this paragraph (from [R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing)) suggests. We also received a suggestion to do it that way for the websocket package, which is GPL-2 licensed but includes C/C++ libraries with various licenses. https://github.com/rstudio/websocket/blob/5281bd4332c1843a421181263d54b7241aa215b6/cran-comments.md

I think that in general, it's good to have a normal LICENSE file that follows the same standard used by other open source projects.

**Comment by jennybc** [comment]
@wch The current logic of `usethis::use_mit_license()` satisfies both the open source world and CRAN. We put a copy of the MIT license in `LICENSE.md` and Rbuildignore it and use `LICENSE` for the short year + copyright holder(s) template.

**Comment by wch** [comment]
That sounds like the inverse of what I suggested, but if that's the way to pass `R CMD check`, I guess that's the way to do it. 

That reminds me: another thing that could really use clarification is how to handle the inclusion of third-party libraries with their various licenses. We've done it a few different ways in different repos, mostly because over time, CRAN has changed what they've told us to do.

**Comment by jennybc** [comment]
> how to handle the inclusion of third-party libraries with their various licenses

My most recent experience of this is with readxl and I was also instructed to put this in `LICENSE.note` (readxl is GPL-3, libxls is BSD 2):

https://github.com/tidyverse/readxl/blob/master/LICENSE.note

And then the authors of the embedded libraries are also listed as `ctb` and `cph`. This all seems consistent with the websocket notes, yes?

**Comment by wch** [comment]
What you have in readxl does appear to be consistent with what they asked for with websocket.

One thing that's missing from both packages is actual license text for the package itself; CRAN doesn't think it's important, but I think we should try to figure out some way to include it.

Just to add a bit of historical context: with Shiny, it took some back and forth before CRAN was satisfied, and the end result is the [DESCRIPTION](https://github.com/rstudio/shiny/blob/1a8b36f06dd96919843a454da6e9eb26986a1659/DESCRIPTION#L61) has `License: GPL-3 | file LICENSE`, and the text of the licenses for the included libraries are in [LICENSE](https://github.com/rstudio/shiny/blob/1a8b36f06dd96919843a454da6e9eb26986a1659/LICENSE).

**Comment by jennybc** [comment]
@Hadley Is this issue on your radar? I believe it's our oldest!

**Comment by hadley** [comment]
Yes, this is mostly handled in the new license chapter, so I think we can close.
