### ISSUE TITLE
Chapter on CRAN policies: trademarks and package names?

### ISSUE THREAD

**Issue by realAkhmed** [hadley/r-pkgs#325]
It looks like there is a potentially dangerous CRAN-policy mistake that is not mentioned in the book and that new developers are likely to make:  _when the name of the new package contains trademarks_

I may have made that mistake with my [mixpanelR](https://github.com/akhmed1/mixpanelR) and it looks like a similar issue is experienced by @cscheid and [github](https://github.com/cscheid/rgithub) package as described in cscheid/rgithub#29

The aftermath of this mistake can be challenging since it requires renaming the package for CRAN submission.

I wonder if it is something that may be useful in the book when discussing CRAN policies?

**Comment by hadley** [comment]
We need a sentence or two about this in packaging naming advice.

And we need to point to and recommend reading of CRAN policies in the CRAN chapter

**Comment by jennybc** [comment]
The package-naming advice has been expanded since this issue was opened. This issue would be in elementary school by now!
