### ISSUE TITLE
documenting data

### ISSUE THREAD

**Issue by jmarca** [hadley/r-pkgs#329]
I was looking up how to include data in a package, and I see that it should be documented, but there is no guidance on *where* to put the documentation.

Obviously the documentation can't go in the .rda file.  Can it go anywhere? Is there a best practices place to put it?

**Comment by hxd1011** [comment]
Hi, James, Please see following figure (Extracted from
http://r-pkgs.had.co.nz/data.html )


[image: Inline image 1]

**Comment by jmarca** [comment]
thanks for the reply, but the inline image include you reference got eaten by the internet.

**Comment by hadley** [comment]
Just search http://r-pkgs.had.co.nz/data.html for "documenting data"

**Comment by jmarca** [comment]
Well, I read that page in the first place and opened this issue because I could not find what I was looking for.

Perhaps I'm not being clear with my question.

When I document functions, I use emacs/ess to generate the Roxygen stuff right above the function in question.

Obviously, one cannot go into the binary RData file to document the data set.

While I'm pretty sure I can put the documentation inside of any of my source R files and the package build step will pick it up, I was asking if there was a preferred place to put the documentation.

The data.html page says nothing that I can find on this preference.

Carefully reading from here: https://github.com/hadley/r-pkgs/blame/master/data.rmd#L64 to here: 
https://github.com/hadley/r-pkgs/blame/master/data.rmd#L92, I see the example of what to write, and advice on new tags, etc, but I do not see advice on *where* to write it.

To use the example given in the documenting data section, I find the diamonds data file in 
`data/diamonds.rda`.  Just the binary, as expected.  Then I looked in man/diamonds.Rd and see [Please edit documentation in R/data.R](https://github.com/hadley/ggplot2/blob/master/man/diamonds.Rd#L2).  Looking up that file, I see the git commit comment: "Eliminate useless package doc. Move data doc into own file" which implies that there is a package doc that is an option, but that you've chosen instead to use data.R to place your documentation.

Just to double check, I do not see any "data.R" when searching the data.html page.

So a suggested edit...hmm, probably best to edit the doc directly to make a pull request.

My text echoes https://github.com/hadley/r-pkgs/blame/master/man.rmd#L295 "I usually put this documentation in a file called `<package-name>.R`....

**Comment by jmarca** [comment]
made pull request #330 with my recommended fix
