### ISSUE TITLE
why the recommendation to export methods for internal S3 generics?

### ISSUE THREAD

**Issue by jackwasey** [hadley/r-pkgs#343]
"However, I recommend exporting every S3 method you write because it's simpler and makes it less likely that you'll introduce hard to find bugs." in the Namespaces page.

AFAICT, if the S3 generic function is not exported, exporting the S3 methods results in polluting the exported namespace with the S3 methods. FWIW I'm using `#' @keywords internal` also. When the generic is exported the namespace is unchanged whether they are exported or not. Given these things, I don't understand the recommendation.

```
roxygen2   * 5.0.1       2015-11-11 CRAN (R 3.2.3)
```

**Comment by hadley** [comment]
Exporting them does no harm; failing to export introduces subtle bugs.
