### ISSUE TITLE
loadNamespace vs requireNamespace

### ISSUE THREAD

**Issue by jackwasey** [hadley/r-pkgs#344]
You write that `loadNamespace` is only used internally, and not recommended. However, it seems that it may be useful where you normally recommend `requireNamespace`. Looking at the source for `requireNamespace` it is a very thin wrapper to run `loadNamespace` in a `tryCatch`.

If the package writer just wants an error if the package user invokes a function with an absent requirement from Suggests, `loadNamespace` would seem like a reasonable choice.

**Comment by hadley** [comment]
I remain confident that there's no situation where `loadNamespace()` is needed. While `requireNamespace()` is wrapper, it expresses the semantics more clearly.
