### ISSUE TITLE
use a vignette-containing example in Package structure

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#349]
The explanations and diagram re: source vs bundled vs binary are super useful:

http://r-pkgs.had.co.nz/package.html#package

It would be even better if the example package included some vignettes, so we could track how they are represented in the different package forms.

**Comment by jennybc** [comment]
Oh it's sort of there: vignettes/ --> inst/doc --> /doc. So maybe nevermind. But then why is there no build/vignette.rds in the bundle view? And the vignette source in vignettes/ persists in the bundle, but is not present in the diagram. Sorry, I have vignettes on the mind.....

**Comment by jennybc** [comment]
In 2nd edition, make sure recommended vignette workflow addresses #395: the package needs to be installed in order for `browseVignettes()` to work.

**Comment by hadley** [comment]
Maybe we should now include creating a vignette in the whole game chapter?

**Comment by jennybc** [comment]
This appears to be covered by #587.
