### ISSUE TITLE
expand documentation on how to document S3 generics, classes, methods

### ISSUE THREAD

**Issue by maxheld83** [hadley/r-pkgs#388]
Being a little dense as I am, it took me a while to understand what I had to do to make sure my own S3 methods `MyHappyFunction.array()` were documented just like  `print.array()` and friends.

Your S-O post helped me do it: http://stackoverflow.com/questions/7198758/roxygen2-how-to-properly-document-s3-methods

Perhaps other people are also dense, like me.

I'd be happy to add that with a couple of sentences in a PR; just wanted to check back first with you whether you'd be open to that.

**Comment by hadley** [comment]
Thanks for the offer of PR, but we'll be rewriting this chapter for the 2nd ed, so probably easiest just for us to do it.

**Comment by hadley** [comment]
I think this is now superseded by the the roxygen2 website. We'll certainly mention documenting S3 generics/methods when we update the documentation chapter, but I think most of the details can now live in roxygen2 itself.
