### ISSUE TITLE
p. 39: Saving options

### ISSUE THREAD

**Issue by gmaubach** [hadley/r-pkgs#402]
Hi Hadley,

I do not understand the command sequence for saving options. Shouldn't it be that way:

old <- options()
options(stringsAsFactors = FALSE)
on.exit(options = old, add = TRUE)

and likewise

old <- getwd()
setwd(tempdir())
on.exit(setwd(old), add = TRUE) ?

If I am mistaken please say so.

Kind regards

Georg

**Comment by jennybc** [comment]
The code reflects common best practice. When these assignments are made, the existing values are returned. Here's a quote from the docs for `options()`:

> For uses setting one or more options, a list with the previous values of the options changed (returned invisibly).

`setwd()` behaves in a similar fashion.
