### ISSUE TITLE
p. 35: devtools::use_package (here: Import and Suggests)

### ISSUE THREAD

**Issue by gmaubach** [hadley/r-pkgs#403]
Hi Hadley,

I follow your workflow throughout the book. When reading p. 35 I tried to use devtools::use_packages("mypackage") on my newly created package but got the error:

Error: mypackage must be installed before you can take a dependency on it

At this point of time (in the book) I have not yet loaded my newly created package.

Should there be another step first?

Kind regards

Georg

**Comment by jennybc** [comment]
The error message suggests that `"mypackage"` is not currently installed. I also wonder if `"mypackage"` is possibly the package you are developing? Which would be incorrect usage.

The `use_package()` function is meant to be called with *other* packages as argument, i.e. a package you want to depend on. And that package must already be installed.
