### ISSUE TITLE
Failed to install devtools

### ISSUE THREAD

**Issue by wiaidp** [hadley/r-pkgs#406]
I used to rely (succesfully) on your contribution for setting-up my MDFA-package on gitHub. I just installed the most recent versions of R and Rstudio and I tried to install your package on my machines (one running Windows 7, the other two computers running Windows 10).  Strangely, I got the same error "Error : package 'devtools' is not installed for 'arch = i386'" on all three machines. I searched thoroughly on the web, trying to identify the source of this error and I must admit that I failed to do so, at least so far. In particular, I meticulously reread and followed the "Getting Started" section on your website (http://r-pkgs.had.co.nz/intro.html). Can you infer some advice from the following output (the error message is at the end)? I installed Rtools and all libraries (including the incriminated devtools) seem to be properly installed. 

> devtools::install_github("hadley/devtools")
Downloading GitHub repo hadley/devtools@master
from URL https://api.github.com/repos/hadley/devtools/zipball/master
Installing devtools
Downloading GitHub repo r-pkgs/pkgload@master
from URL https://api.github.com/repos/r-pkgs/pkgload/zipball/master
Installing pkgload
Installing 1 package: bitops
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/bitops_1.0-6.zip'
Content type 'application/zip' length 36404 bytes (35 KB)
downloaded 35 KB

package ‘bitops’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\wlmr\AppData\Local\Temp\RtmpKEF1jE\downloaded_packages
Downloading GitHub repo r-pkgs/pkgbuild@master
from URL https://api.github.com/repos/r-pkgs/pkgbuild/zipball/master
Installing pkgbuild
Downloading GitHub repo mangothecat/callr@master
from URL https://api.github.com/repos/mangothecat/callr/zipball/master
Installing callr
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wlmr/AppData/Local/Temp/RtmpKEF1jE/devtools74c526c27ca/r-pkgs-callr-c2fb27d"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'callr' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (callr)
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wlmr/AppData/Local/Temp/RtmpKEF1jE/devtools74c226713ab/r-pkgs-pkgbuild-5ed87aa"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'pkgbuild' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (pkgbuild)
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wlmr/AppData/Local/Temp/RtmpKEF1jE/devtools74c3fa0113b/r-pkgs-pkgload-3a96cf2"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'pkgload' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (pkgload)
Skipping install of 'callr' from a github remote, the SHA1 (c2fb27d6) has not changed since last install.
  Use `force = TRUE` to force installation
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/wlmr/AppData/Local/Temp/RtmpKEF1jE/devtools74c29365841/hadley-devtools-d8ab190"  \
  --library="C:/Program Files/R/R-3.3.3/library" --install-tests 

* installing *source* package 'devtools' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error : package 'devtools' is not installed for 'arch = i386'
Fehler: Laden fehlgeschlagen
Ausführung angehalten
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.3.3/library/devtools'
* restoring previous 'C:/Program Files/R/R-3.3.3/library/devtools'
Warnung in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)
  Problem C:\Program Files\R\R-3.3.3\library\00LOCK-hadley-devtools-d8ab190\devtools\libs\x64\devtools.dll nach C:\Program Files\R\R-3.3.3\library\devtools\libs\x64\devtools.dll zu kopieren: Permission denied
Error: Command failed (1)
>

**Comment by hadley** [comment]
If you're still having problems, the right place to fill an issue is the devtools repo
