### ISSUE TITLE
Include error messages from `expect_something` functions in R markdown document

### ISSUE THREAD

**Issue by symbolrush** [hadley/r-pkgs#435]
Including error messages from `expect_something` functions in R markdown does not work. Setting `error = TRUE` in the chunk options does not prevent `knit` from failing to knit the document.
See also: https://stackoverflow.com/questions/47330385/include-error-messages-from-testthat-in-r-markdown-document

**Comment by hadley** [comment]
This maybe fixed, @jennybc please check

**Comment by jennybc** [comment]
This **is** fixed.

If I put this chunk in an `.Rmd`:

<pre><code>```{r error = TRUE}
testthat::expect_true(FALSE)
```</code></pre>

I get this back out:

``` r
testthat::expect_true(FALSE)
#> Error: FALSE isn't true.
```
