### ISSUE TITLE
Cautionary tales about changing global state

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#447]
For possible inclusion as a sidebar in a future edition, somewhere in this vicinity:

https://github.com/hadley/r-pkgs/blame/master/r.rmd#L305

Two recent-ish examples around random number generation that show how careful you need to be when changing global state in your package.

ggplot2's use of a random number to display a message upon startup (but only in interactive sessions)

  * A decent place to start in the Twitter conversation: https://twitter.com/jimhester_/status/954349179530248193
  * PR changing the behaviour: https://github.com/tidyverse/ggplot2/pull/2409

htmlwidgets touching the seed

  * Reports showed up on dplyr, even though that had nothing to with the root problem: https://github.com/tidyverse/dplyr/issues/2124.
  * Ditto rmarkdown https://github.com/rstudio/rmarkdown/issues/980
  * Actual resolution: https://github.com/ramnathv/htmlwidgets/pull/265

Paraphrasing discussion elsewhere: "don't touch things that don't belong to you and if you have to, you need to be super careful to wipe all your sticky fingerprints off everything"

**Comment by jennybc** [comment]
And another little tale, also re: random numbers from @topepo:

https://github.com/topepo/caret/issues/452#issuecomment-232669260

**Comment by hadley** [comment]
I think this is now covered by https://r-pkgs.org/package-within.html#package-within-side-effects and https://r-pkgs.org/r.html#manage-state-with-withr

**Comment by jennybc** [comment]
I think we should mention this specific thing somewhere, by which I mean "random number generation in `.onLoad()` or `.onAttach()`". I just accidentally did this in reprex, luckily caught it immediately because of a test, and gained a renewed appreciation for this gotcha.
