### ISSUE TITLE
Finish/fix a paragraph re C/C++ dev workflow

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#456]
This paragraph ends very suddenly and it's not clear how you meant to end it @hadley.

The advice re `load_all()` might be stale, at least for the 2nd edition, but you should at least complete the sentence before declaring 1st edition to be frozen.

http://r-pkgs.had.co.nz/src.html#src-workflow

> When developing C or C++ code, it’s usually better to use RStudio’s Build & Reload instead of `devtools::load_all()`. If you have C objects that persist between reloads, and you change the data structure, then it’s

Issue raised and discussed some in PR #438, now closed.

**Comment by hadley** [comment]
Better to use install and restart: otherwise there’s a high chance of crashes due to differences between versions of your C code.
