### ISSUE TITLE
Revisit C/C++ development recommendations

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#457]
See discussion on this now-closed PR: #352.

[Comment](https://github.com/hadley/r-pkgs/pull/352#issuecomment-364679544) from @jimhester should potentially inform the revision:

> The described behavior of `load_all()` ... it does recompile both header and object files as necessary. It can still be problematic to use `load_all()` when developing on windows due to OS locking of the shared library, but on POSIX machines it works well.
> 
> .... MAKEFLAGS I feel is better set in your shell environment and if you want to turn off optimizations I think it is much more clear to do so in CFLAGS, CXXFLAGS etc. than using the LTO hack. If the LTO setting remains it would need much more descriptive text on why it works and why it is not an issue to override any existing LTO settings etc. Also generally I would recommend -Og rather than -O0 when doing development <https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html>

**Comment by hadley** [comment]
We need to think about where all C++ material should live. So it stay divided across adv-r and r-pkgs or be centralised somewhere?
