### ISSUE TITLE
Connect me to the O'Reilly version

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#458]
@hadley

I notice that some of the issues addressed by recently merged PRs have already been fixed, in slightly different ways, in my printed copy of the book.

I'm not saying I'll transfer it all, but is it easy to grant me access to whatever O'Reilly considers the final version of the 1st edition?

**Comment by hadley** [comment]
I can probably get it to you, but it's in asciidoc, so transferring the fixes would be a lot of work. I don't think it's worth it.

**Comment by jennybc** [comment]
OK. When I am sufficiently motivated, I can always check my hard copy. I'll raise it again if it keeps coming up.

**Comment by hadley** [comment]
There will also be another set of O'Reilly copy edits prior to publication.
