### ISSUE TITLE
🎆 Big picture

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#462]
* [x] "whole game chapter" (#452)
* [x] remove detailed coverage of markdown from vignettes, link out to \<fill this in\>
* [x] remove git + github chapter, link out to [Happy Git](http://happygitwithr.com) (#526)
* [x] state high-level style principles and why it matters, link out to <http://style.tidyverse.org> for details
* [x] rename release to "Release on CRAN"
* [ ] think about other sorts of release
* [ ] marketing chapter, including pkgdown
* [x] continuous integration chapter
* [x] README + NEWS etc chapter

**Comment by jennybc** [comment]
Jenny proposals

* [ ] better coverage of data packages ... possibly with its own "whole game" chapter
* [ ] advice on which practices to follow for your first package vs your 10th:
  - 1st package: just get the damn thing to work ... and maybe pass R CMD check
  - 10th package: realize that setting up moving parts early pays off (tests and CI especially). Much easier to do the incremental work as you go than to "add tests " or "turn on travis" after months of development.

**Comment by hadley** [comment]
Maybe it's worth having a wider selection of sidebars? Like you should care about this if:

* You want to submit to CRAN
* Your package has >1 revdeps
* Your package has >100 revdeps

**Comment by jennybc** [comment]
I feel this issue is no longer a good summary of what needs to be worked on.
