### ISSUE TITLE
"In the wild"

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#463]
Have some structure for pointing to packages written by other people

**Comment by jennybc** [comment]
Thinking out loud.

We'd need to highlight specific topics in great need of wild examples. I'm looking at you, roxygen2 and testthat.

A system for collecting structured community input on the above: Link to source (presumably SHA'd GitHub links to files or lines ... probably in the read-only cran mirror of said package) + some explanatory text. Make this input available with no implied guarantee of quality/relevance but assume everyone is acting in good faith.

Use selections from the above for more formal inclusion in the book.

This has obvious ties to some new content re: helping people help themselves: tips for searching GitHub (@jimhester gave a really nice treatment of this in my rstudio::conf workshop).

**Comment by jennybc** [comment]
I feel like various ways of programmatically studying the ecosystem are under-appreciated and under-documented.

More examples: The desc package, the various METACRAN services & APIs (<https://www.r-pkg.org/services#api>).

**Comment by jennybc** [comment]
This goes naturally with #645, in the sense of "a general banner of how to solve one's own ongoing package development problems, how to keep learning more, etc."

I am no longer keen on the idea of collecting community input re: "in the wild" examples, as I think that creates more problems than it solves. It's a version of all doomed "I shall curate a list!" projects that inevitably become stale, uneven, and disorganized.

I am still keen on us highlighting examples from "the wild" in the text, teaching people how to search GitHub effectively, pkgsearch, METACRAN APIs, etc.

(Also, roxygen2 and testthat are dramatically better documented now than they were in February 2018.)

**Comment by hadley** [comment]
Yeah, agreed on the problems of "we shall make a list".
