### ISSUE TITLE
More in-depth treatment of testing

### ISSUE THREAD

**Issue by jenniferthompson** [hadley/r-pkgs#477]
As updates are considered for a second version: It would be really helpful to expand the excellent introduction to testing to cover best practices for more complex tests, such as how to store objects that should be used in >1 test script.

**Comment by alexpghayes** [comment]
Brainstorm of additional possible topics:

- Tests that rely on external code, especially in other languages. For example, suppose you want to test against a reference implementation in MATLAB.
- Tests whose results live in data files
- Testing formula interfaces (in particular using `splines::ns` and `splines::poly`)

**Comment by alexpghayes** [comment]
Perhaps out of scope, but Google published [the following guide on testing ML systems](https://www.eecs.tufts.edu/~dsculley/papers/ml_test_score.pdf) which has several sections relevant to modelling packages.

**Comment by aronatkins** [comment]
Include recommendations for file naming, context, helpers, and how one might use setup and teardown (for a test directory and within individual tests).

**Comment by aronatkins** [comment]
Include recommendations for stubbing/mocking of different "things". Base R, packages, functions, variables.. things like `myfunction <- function(a, b, quitter=quit) { ... }` that let you replace the `quit` implementation in test.

**Comment by fbchow** [comment]
- don't need `:::` in unit tests. 
  - `pkgname:::fn()`. 
- best practices for initializing specific global variables  
  -  mitigating R CMD check note

**Comment by dlebauer** [comment]
A few other topics that could be of interest:
* best practices for generating and including example data
  * create object inline, or put file in tests/testthat/data or ? 
* best practices for tests that rely on external APIs
