### ISSUE TITLE
A chapter specific to modelling packages

### ISSUE THREAD

**Issue by alexpghayes** [hadley/r-pkgs#481]
So far as I'm aware, there are some standards for developing modelling packages, but there isn't a canonical reference on best practices (the most I could find was [this](https://developer.r-project.org/model-fitting-functions.html) from 2003). I think it would be fantastic to have a new chapter focused specifically on packages that implement new statistical methods or algorithms. Some potential topics:

- user friendly interfaces
- formulas, model.frame, term objects, etc
- some explanation of why and how to save the function call
- generally what kinds of things should go into a model object, giving model objects a class so other people can extend them
- testing against existing software
- methods to implement
- examples of tried and true workflows

I'm sure there are tons of topics that I'm missing here as well.

**Comment by hadley** [comment]
This would be nice to have, but I think it's out of scope for R packages.
