### ISSUE TITLE
Thorough treatment of dependencies

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#486]
* Why importing tidyverse is a bad idea
* Why caring too much about imports is a bad idea
* Why having many imports for a low-level package is a bad idea

Plus some good ideas :smile:

cc @batpigandme

**Comment by batpigandme** [comment]
Hey, there's a reason the Ten Commandments is made up of interdictions… ❌

**Comment by jennybc** [comment]
Does this subsume #485?

**Comment by hadley** [comment]
I don't think so - that's advice on using the Depends field; this is more general advice on managing dependencies.

**Comment by jennybc** [comment]
We clearly need a chapter about dependencies. I have now created such a label.
