### ISSUE TITLE
Add additional details on examples section of function documentation

### ISSUE THREAD

**Issue by alexpghayes** [hadley/r-pkgs#491]
- Do we need to load packages in `Imports` in examples in documentation, or should examples be self-contained like reprexes?
- Do we need to guard against `Suggested` packages? i.e. something like:

```r
if (requireNamespace("suggested_package", uietly = TRUE)) {
  library(suggested_package)  # so you can copy paste the example minus the if brackets and it'll run
  ...
}
```

- Is there a convenient workflow for writing the examples? Currently I write the example in a temporary R file, check it with `reprex`, copy it into the documentation, and then spend a minute or two adding `#'` to the start of each line.

**Comment by jennybc** [comment]
Good suggestions!

> Is there a convenient workflow for writing the examples?

I write them *in situ*. RStudio makes it very easy to get the `#' ` automatically and allows you to execute the examples from roxygen comments with the same keystrokes used in `.R` and `.Rmd`.

**Comment by jennybc** [comment]
Ah, it's true that the normal indentation assistance is not available in RStudio in oxygen comments. Taking this to another another channel...

**Comment by moodymudskipper** [comment]
With Alt + select you can can select the beginning of each line and type `#' ` only once.

Another option is to make your temp file permanent and use `#'  @example path/to/file.R`

Then you don't need the `#'` at all.

**Comment by alexpghayes** [comment]
Thought that may be more style related: having 5-25 lines of data munging at the beginning of the example can obscure the code. For example:

**Not my favorite**

```
## data
data("CigarettesSW", package = "AER")
CigarettesSW$rprice <- with(CigarettesSW, price/cpi)
CigarettesSW$rincome <- with(CigarettesSW, income/population/cpi)
CigarettesSW$tdiff <- with(CigarettesSW, (taxs - tax)/cpi)

## model 
fm <- ivreg(log(packs) ~ log(rprice) + log(rincome) | log(rincome) + tdiff + I(tax/cpi),
  data = CigarettesSW, subset = year == "1995")
summary(fm)
summary(fm, vcov = sandwich, df = Inf, diagnostics = TRUE)
```

**Better**

```
data("CigarettesSW", package = "AER")

fm <- ivreg(log(packs) ~ income | population, data = CigarettesSW)
summary(fm)
```

I see this in `broom` a bunch when someone copy-pastes an example from a modelling function that is supposed to reproduce an analysis from a paper, etc.
