### ISSUE TITLE
"The main difference is that [...]. There are no other differences."

### ISSUE THREAD

**Issue by moodymudskipper** [hadley/r-pkgs#492]
From the NAMESPACE chapter:

> The main difference is that where Imports just loads the package, Depends attaches it. There are no other differences.

The statement contradicts itself.

Replace "main" by "only" ? or "no other difference" by "no other important difference" ?

**Comment by jennybc** [comment]
This chapter is still awaiting revision, so I'm confident these passages will get some rewording (and we'll beat these comments in mind). I'm not going to get drawn into wordsmithing in these subtle ways on text slated for an update.
