### ISSUE TITLE
http://r-pkgs.had.co.nz/src.html#c-best-practices - checking a command

### ISSUE THREAD

**Issue by sn248** [hadley/r-pkgs#496]
The book says to to start `R` with llvm debugger, type `process start`. I started `R` as `R --debugger=lldb`. I get the following prompt

```
(lldb) target create "/Library/Frameworks/R.framework/Resources/bin/exec/R"
Current executable set to '/Library/Frameworks/R.framework/Resources/bin/exec/R' (x86_64).
(lldb) 
```

Then, when I type `process start` (as mentioned here), I get `invalid command 'process start'`. 

Can this be updated to the right commands? Thanks.

**Comment by sn248** [comment]
Just an update, after `R --debugger=lldb`, the command to run `R` should be `run`

**Comment by jennybc** [comment]
I think this content has since been removed.
