### ISSUE TITLE
_build.sh: No such file or directory

### ISSUE THREAD

**Issue by miguelmorin** [hadley/r-pkgs#502]
I clone the git repository to my computer with `git clone https://github.com/hadley/r-pkgs`, then I open `r-pkgs.Rproj` in RStudio, and run Build > Build All (Command-Shift B). I get this error:
```
/bin/sh: ~/r-pkgs/_build.sh: No such file or directory

Exited with status 127.
```

I succeeded in building the book Advanced R following a similar procedure and Advanced R does not have a `_build.sh` either. Am I doing something wrong?

I assign the copyright of this contribution to Hadley Wickham.

**Comment by jennybc** [comment]
The mechanics of this book are quite old now. We will reset for a second edition soon and one of the first things to change will be this, i.e. it will switch over to whatever Hadley considers current best practice (probably what he's doing in Advanced R).

We'll just leave this alone for now.

**Comment by miguelmorin** [comment]
Yes, I confirm that Advanced R works quite well. Do you have an idea of when that second edition will happen?

**Comment by jennybc** [comment]
I will start to work on it soon and I think @hadley will start exerting external pressure, once he finishes the next edition of Advanced R. But it will clearly be more of a 2019 thing than 2018.

**Comment by miguelmorin** [comment]
Thank you @jennybc . I will scrape the book from the online source instead.
