### ISSUE TITLE
testdata example no longer supported

### ISSUE THREAD

**Issue by DougManuel** [hadley/r-pkgs#507]
the example for `inst/extdata` is no longer updated by the author and supported in current R packages. https://github.com/hadley/r-pkgs/blob/master/data.rmd#L111

Suggest updating the example for `gapminder` package. https://github.com/jennybc/gapminder

I can PR if you are interested in help. 

Gapminder is a great legacy to support. As well, this package is nicely documented with the datasets in both .rda and also .tsv. So, helpful to contrast the different data approaches.

**Comment by jennybc** [comment]
Thanks!

This is the sort of update we'll tackle in the second edition, which is definitely happening but has not started yet. There's no point in making a PR at this point, because we want to freeze current version, tag, update mechanics, then initiate.

So we'll leave this open for now.

**Comment by hadley** [comment]
Fixed in 71d23c5750a542f475cb80249595ad30a36c25d9
