### ISSUE TITLE
Package-level documentation 

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#531]
Removing this from the Whole Game. Make sure the content already exists or gets introduced somewhere.

---

## `use_package_doc()`

Let's start adding package-level documentation. Your package as a whole can have its own `.Rd` file. You can see an example by entering `package?tibble` in R Console. Read more about the uses of package-level documentation [later in this book](#man-packages).

Set this up with `devtools::use_package_doc()`:

```{r use-package-doc, eval = create}
use_package_doc()
```

This creates a peculiar dummy file `R/foofactors-package.R` with a roxygen header, that is just documenting `NULL`. The purpose of this is simply to trigger the generation of a package-level `.Rd` file. By default, this package-level documentation will be automatically generated from metadata in `DESCRIPTION`. To achieve this, we re-`document()` the package.

```{r document-package, eval = create}
document()
```

```{r commit-package-doc, echo = debug, comment = NA, eval = create}
paths <- unlist(status(repo))
add(repo, path = paths)
commit(repo, message = "Add package-level doc, re-document()")
```

Have a look at your new package-level docs:

```{r eval = FALSE}
?foofactors
```

**Comment by dmurdoch** [comment]
This comment and the current text need updating:  roxygen now supports the `"_PACKAGE"` sentinel for automatically setting up package documentation, as described here:  https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html#packages

**Comment by hadley** [comment]
Not 100% this will remain in the book, so might need to go into roxygen2 vignette instead.

**Comment by jennybc** [comment]
I lean towards covering package-level help doc because it's also where we recommend doing this sort of importing (example is from stringr):

```
## usethis namespace: start
#' @import stringi
#' @import rlang
#' @importFrom glue glue
#' @importFrom lifecycle deprecated
## usethis namespace: end
NULL
```
