### ISSUE TITLE
Rescue check() results in Whole Game when rendered on travis

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#532]
@gaborcsardi or @jimhester 

Does either of you spot why `check()` isn't truly running here?

https://r-pkgs.org/whole-game.html#check

Specifically this is the problem. Note the `cannot coerce ‘FALSE false’ to logical`:

```
   Warning in config_val_to_logical(check_incoming) :
#>      cannot coerce ‘FALSE false’ to logical
#>    Error in if (check_incoming) check_CRAN_incoming(!check_incoming_remote) : 
#>      missing value where TRUE/FALSE needed
#>    Execution halted
```

which I don't see locally. The book is built on travis fwiw.

**Comment by jimhester** [comment]
Yeah, use devel devtools to fix, it was fixed in https://github.com/r-lib/devtools/commit/9780c9fefd588f4b84128d4db8b8a91c5708ce66
