### ISSUE TITLE
reference info re: analysis packages

### ISSUE THREAD

**Issue by jameelalsalam** [hadley/r-pkgs#534]
from twitter exchange w/ Jenny Bryan:
https://twitter.com/JennyBryan/status/1095362539691565056

**Comment by jennybc** [comment]
Thought dump: the book already discusses data packages, in some detail. Analysis packages should also be defined and, at the very least, we should provide links to good resources about that.

**Comment by jennybc** [comment]
This feels more out of scope to me now.
