### ISSUE TITLE
Compiled code, best practices, clang, Windows

### ISSUE THREAD

**Issue by rdiaz02** [hadley/r-pkgs#538]
Section 11.1.5 (Compiled code, best practices) says: 
"Use clang instead of gcc to compile your C++ code: it gives much better error messages. You can make clang the default by creating a .R/Makevars (linux and mac) or .R/Makevars.win (windows) file in your home directory that contains:

CXX=clang++"

I do not think it is possible to use clang under Windows for package development (not with the current Rtools).  I suggest deleting "or .R/Makevars.win (windows)" and making it explicit that this is not possible with Windows.

**Comment by jennybc** [comment]
The content on compiled code will either get heavily rewritten or will be removed in favour of detailed content that lives elsewhere. The world has changed so much since this issue was opened that a ground up rewrite will be necessary.
