### ISSUE TITLE
Should this book document usage of non-code-generated static images within Rmd vignettes?

### ISSUE THREAD

**Issue by MilesMcBain** [hadley/r-pkgs#540]
To do this is a bit tricky and hard to Google. I got lucky with a tip off from the rOpenSci slack, so I think it would be good to put it on the record in the section on Vignettes here.

It would make sense to me as another subsection of 7.3. Here's some rough example text:

#### Static Images

Images that are not generated as part of the vignette build should be placed in the `vignettes/` folder and included in the vignette source using `knitr::include_graphics()` instead of the usual `![](image link)`. This can be done using an inline R expression like so:

``` `r knitr::include_graphics("<image_name>.png")` ```

The package build process needs to be instructed to copy those images along with the built vignettes into the correct folder. To do this you must create a file called `.install_extras` in `vignettes/` that contains Perl-style regular expressions, one per line, that will match image files to be copied.

For example, If you needed the build process to copy over all images with the `.png` extension from `vignettes/` you would create a `vignettes/.install_extras` with a single line: 

```
\.png$
```

**Comment by MilesMcBain** [comment]
I see from the "Big Picture" issue that the plan is to remove the markdown section and link to markdown documentation. This still feels to me like something that is specific to package dev.

**Comment by MilesMcBain** [comment]
Okay so it turns out that users do not need `.install_extras` when using `include_graphics()` since that function will embed them directly in HTML as base64 encoded strings. The text to reflect this might become:

#### Static Images

Images that are not generated as part of the vignette build should be placed in the `vignettes/` folder and included in the vignette source using `knitr::include_graphics()` instead of the usual `![](image link)`. This can be done using an inline R expression like so:

``` `r knitr::include_graphics("<image_name>.png")` ```

For HTML vignettes, these images will be embedded in the document as base64 encoded URIs.

For pdf??

**Comment by hadley** [comment]
If I do:

```R
remotes::install_github("https://github.com/hadley/kittens", build_vignettes = TRUE)
vignette("kittens")
```

Both images look fine, so I don't think there's anything special we need to document?
