### ISSUE TITLE
check for unused imported packages

### ISSUE THREAD

**Issue by EmilHvitfeldt** [hadley/r-pkgs#541]
A section on checking if all the imported packages are being used somewhere in the package.

I wrote some crude code that might form the basis on such a check.

```r
library(magrittr)
dependencies <- desc::desc_get_deps()$package %>% setdiff("R")
used <- itdepends::dep_usage_proj("~/package") %>% dplyr::pull(pkg) %>% unique()

dependencies %>% setdiff(used)
```

**Comment by jennybc** [comment]
I feel that we should rely on `R CMD check` to alert us to this vs. rolling one's own.

Now, I know that whether this phenomenon is reported (or not) definitely has to do with the settings in force during the check, as this particular check has historically been unevenly reported across different CRAN flavours. Which really makes this an issue for rcmdcheck and I'm optimistic that we are making progress on getting a handle on how to replicate various CRAN check configurations. I don't think there's currently anything to do here.
