### ISSUE TITLE
More on .onUnload?

### ISSUE THREAD

**Issue by ppanko** [hadley/r-pkgs#545]
This is closer to a question than an issue in any real sense. If I'm barking up the wrong tree here, please feel free to close the issue.

Seems like both "Writing R Extensions" and "R Packages" agree that in general, a package that builds dynamic libraries should clean-up on detach/unload. On one hand, cleaning up clearly prevents some "spooky action" from cropping up, especially in the context of package development. On the other hand, there are some popular packages (e.g. testthat, tidyr, vctrs, Rcpp) that avoid using `.onUnload` or `library.dynam.unload` explicitly, as far as I can tell.

My question is, has anything changed in the "best practices" of using `.onUnload` as described in this text, or are the packages I referenced part of a special case outside the purview of typical DLL clean-up?

**Comment by hadley** [comment]
I don't think so; in general it's not possible to 100% cleanly unload a loaded package (especially wrt S3 and S4 method registration) so in my experience it's not worth worrying about `.onUnload()`. And if there ever are problems it just easier to fix them by restarting R.
