### ISSUE TITLE
Talk about setup / teardown and helper files

### ISSUE THREAD

**Issue by jimhester** [hadley/r-pkgs#556]
Also emphasize that in most cases code should go in these rather than in `tests/testthat.R`, since the latter is not executed with `devtools::test()`.

This is a pretty common source of issues, for two recent examples,
  - https://github.com/r-lib/devtools/issues/2038
  - https://github.com/hadley/r-pkgs/issues/483#issuecomment-480200246

But I could dig up more as well if needed.

**Comment by jennybc** [comment]
Also good to cover how this interacts with `devtools::load_all()`.
