### ISSUE TITLE
Minimum R version "supported" by this book

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#564]
Shall we adopt the tidyverse policy of:

> current version, the devel version, and four previous versions of R

?

So, as of June 2019, R 3.7, 3.6, 3.5, 3.4, 3.3, 3.2.

Implication: I can delete sections like this:

https://github.com/hadley/r-pkgs/blob/40a5e5d0f6609ebf606fbb3e62348699412722a3/metadata.Rmd#L149-L151

**Comment by hadley** [comment]
Yeah, I think that's reasonable. We could even consider only supporting 3.3 and up, based on when the book is likely to be published.

**Comment by jennybc** [comment]
Great. I'll go with >= 3.2 for now but reserve the right to consider >= 3.3 if that becomes relevant.
