### ISSUE TITLE
mention `available::available` in the book?

### ISSUE THREAD

**Issue by njtierney** [hadley/r-pkgs#574]
The [`available` package](https://github.com/ropenscilabs/available) is awesome for checking if your R package is available on CRAN, bioconductor, and github. It'd be great to mention it in the R packages book, and I'm happy to submit a PR for this that says something like the following:

```
It is a good idea to spend some time choosing your package name.
You can check if your package name is available for use on CRAN 
by using the [`available` package](https://github.com
ropenscilabs/available), which does the following:

* Checks for validity
* Checks not already available on GitHub, CRAN and Bioconductor
* Searches Urban Dictionary, Wiktionary and Wikipedia for 
unintended meanings

(insert screenshot here?)

While checking if your package name is available, it might also 
be worthwhile to check if the functionality of your package 
already exists - you may save yourself a lot of time using 
existing software rather than writing your own.
```

But I'm not sure where to put it - perhaps:

* at the [start or end end of whole game](https://r-pkgs.org/whole-game.html#the-end-check-and-install)
* in the [section on package naming](https://r-pkgs.org/package-structure.html#naming)
* or in the [release section](https://r-pkgs.org/release.html)

Do you have any thoughts on this?

Also see: https://github.com/r-lib/usethis/issues/808

**Comment by jennybc** [comment]
I think it belongs in the section on package naming. A PR would be great.

**Comment by njtierney** [comment]
OK! PR here: https://github.com/hadley/r-pkgs/pull/575
