### ISSUE TITLE
Chapter 14.15 "Submitting a pull request to another repo" doesn't explain how to submit a PR

### ISSUE THREAD

**Issue by jhuntergit** [hadley/r-pkgs#577]
Chapter 14.15 titled _"Submitting a pull request to another repo"_ doesn't seem to include the steps to submit a pull request to another repo. Maybe I'm missing something totally obvious here. I can follow the whole chapter right up to the end, right before getting to chapter 14.16 _"Reviewing and accepting pull requests_". But there are never steps such as:

```r
# Review the changes (locally) and push
git status
git add .
git commit -m "<message>"
git push -u origin <branch-name>
# Finalize the pull request on GitHub
https://github.com/<user>/<repo>.git > select the “New pull request” button
then “Create pull request” on the subsequent page
and then “Create pull request” again on the page that allows you to add comments
```

Is the graphic at the end of chapter 14.15 supposed to explain something similar to the steps I just listed? How do I actually submit the pull request? I'm leaving this chapter wondering _how_? Thank you.

**Comment by jennybc** [comment]
The Git/GitHub content of this book is going to basically be removed and, instead, link out to [Happy Git and GitHub for the useR](https://happygitwithr.com).

See #526 and #462
