### ISSUE TITLE
Missing toolbar in Chapter 9

### ISSUE THREAD

**Issue by datarttu** [hadley/r-pkgs#578]
The toolbar with search, font settings, etc. seems to be missing in Chapter 9 (Namespace) of the second edition [currently available online](https://r-pkgs.org/namespace.html). If I change font settings in one of the other chapters (where the toolbar works well), they reset to the default white sans theme in this chapter, working correctly again after returning to other chapters. Also, the sidebar contents seem to be completely unfolded in Chapter 9 while they work correctly elsewhere.

I was not able to reproduce the bug locally after rendering the contents of the current repo. Since I don't have much experience with bookdown, I could not figure out whether this is a project- or bookdown-specific issue.

**Comment by jennybc** [comment]
bookdown and the specifics of the r-pkgs site have changed a lot since this was opened.
