### ISSUE TITLE
Badges?

### ISSUE THREAD

**Issue by jameslairdsmith** [hadley/r-pkgs#582]
Is it worth having a section explaining the various kinds of badges along with recommendations for when and where it is appropriate to use them? As a first-time package developer this was something that confused me. Many people seem to use them and there are lot of sources for making them, but there is little explanation (that I can find) of where they are appropriate or useful.

**Comment by jennybc** [comment]
I think this will naturally come up when we revise / add content about README and pkgdown sites.
