### ISSUE TITLE
Diagram reboot: source vs bundled vs binary package

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#587]
Talking about this figure which appears in the chapter about package structure and states:

[![package-files.png](https://github.com/hadley/r-pkgs/blob/main/diagrams/package-files.png?raw=true)](https://github.com/hadley/r-pkgs/blob/main/diagrams/package-files.png)

### Notes:

Remake this, possibly with a different (fictional or deliberately crafted?) package. Things I want to address: `README.Rmd`, `.github/`, CI config, pkgdown, `LICENSE.md`, `data-raw/`, updated treatment of `NEWS.md`, existence of `vignettes/` in tarball, presence of `build/` in tarball, absence of `README.md` in binary form.

Existing diagram does a good job of juxtaposing differences between these package states on disk. Can we also incorporate something about the "horizontal" workflows that move the package from state to state? Or can we make a companion diagram for this?

**Comment by kalaschnik** [comment]
You may even consider using Mermaid very soon
![image](https://user-images.githubusercontent.com/9831678/150876409-b08c736d-0ec9-49f2-88ca-8bc960371844.png)

- Filtered GitHub Public roadmap by mermaid: https://github.com/orgs/github/projects/4247/views/1?filterQuery=mermaid
- Should work like so: https://stackoverflow.com/questions/40803017/how-to-include-diagrammer-mermaid-flowchart-in-a-rmarkdown-file

**Comment by jennybc** [comment]
We will probably stick with PNG or similar as we often use resources like this in multiple other venues, like slides or cheatsheets, etc.

**Comment by ateucher** [comment]
> Can we also incorporate something about the "horizontal" workflows that move the package from state to state? Or can we make a companion diagram for this?

Does Fig 4.2 do this job sufficiently? [![installation.png](https://github.com/hadley/r-pkgs/blob/main/diagrams/installation.png?raw=true)](https://github.com/hadley/r-pkgs/blob/main/diagrams/installation.png)

**Comment by jennybc** [comment]
Yeah 4.2 does document the horizontal workflows. Honestly I can't remember exactly what I was thinking when I wrote that. Maybe I wanted to create a figure that somehow covers both the states and the workflows to move between them? 🤷‍♀️

**Comment by ateucher** [comment]
The one in the cheatsheet also incorporates "In memory" with `library()`, `load_all()` etc, which is quite nice

<img width="528" alt="image" src="https://user-images.githubusercontent.com/2816635/221254935-ab3a98b2-3f5e-4d72-9194-4f02f4fe2553.png">

**Comment by jennybc** [comment]
Yeah, we'll definitely transfer any diagram innovations made in the cheatsheet to the book.

**Comment by jennybc** [comment]
An observation made in #349 which I've closed:

> why is there no `build/vignette.rds` in the bundle view? And the vignette source in `vignettes/` persists in the bundle, but is not present in the diagram.

Double check the vignette specifics in whatever we end up with.

**Comment by jennybc** [comment]
Thoughts:

* We could mention that the *form* of DESCRIPTION changes from source to bundle. As in, all of this stuff shows up:
    ```
    Packaged: 2022-05-25 20:21:49 UTC; jenny
    Author: Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>),
      Jennifer Bryan [aut, cre] (<https://orcid.org/0000-0002-6983-2759>),
      Malcolm Barrett [aut] (<https://orcid.org/0000-0003-0299-5825>),
      RStudio [cph, fnd]
    Maintainer: Jennifer Bryan <jenny@rstudio.com>
    Repository: CRAN
    Date/Publication: 2022-05-25 20:50:02 UTC
    ```
