### ISSUE TITLE
Give the book PARTs decent names

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#590]
?? NAME?? : the "pre meta stuff"

  * Introduction
  * The Whole Game
  * System setup
  * Package structure and state
  * Fundamental package workflows

Package parts: individual files and folders

  * R code (`R/`)
  * Package metadata (`DESCRIPTION`)
  * Object documentation (roxygen comments and `man/`)
  * Vignettes
  * Namespace
  * External data
  * Compiled code
  * Installed files
  * Other components

?? NAME?? : the "post meta stuff"

  * Git and GitHub *Git/GitHub content will become mostly a stub pointing to Happy Git and focus more on value of using a public venue for development, an issue tracker, tagging releases, etc.*
  * Automated checking
  * Releasing a package
  * *will probably gain a chapter on marketing*

**Comment by jennybc** [comment]
Input welcome.

cc @hadley

**Comment by hadley** [comment]
* Getting started
* Package components
* Sharing with others

?
