### ISSUE TITLE
Revise example & recommendation around the personal library location

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#591]
I'm so close to doing this now. I should just conform. Quoting @jimhester from a different channel:

> I run `dir.create(Sys.getenv("R_LIBS_USER"))` once when I update R to a new minor version. Then then use that for my library (it is set to `~/Library/R/3.6/library` by default for R 3.6.x).

**Comment by hadley** [comment]
Yeah, this seems right to me too

**Comment by jimhester** [comment]
This is what I recommended in https://whattheyforgot.org/maintaining-r.html#how-to-transfer-your-library-when-updating-r as well, although it is kind of buried in the rest of the section, maybe we should pull it out into its own section.
