### ISSUE TITLE
Make cache / rebuild situation for Whole Game less bad

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#595]
Currently the only way to re-render that chapter is to clear the full travis cache. This is too costly because it also causes the package cache to rebuild.

Slightly less bad suggestion from @Hadley: introduce a toggle-able chunk at top of this file that can pre-delete its own cache. It still means we need 2 commits to "kick" the Whole game (1 to clear the cache, 1 to cancel the cache-clearing), but it's better than clearing the package cache.

**Comment by jimhester** [comment]
An alternative, have the first chunk depend on an environment variable, then you can just change the value of the environment variable to invalidate the existing cache.

**Comment by jennybc** [comment]
Does that help me avoid a two-step solution? I don't think so, but perhaps I'm missing something.

**Comment by jennybc** [comment]
What keeps it from being rebuilt on the next push? I guess the need for two steps have been moved from the code to the CI settings, which would still be an improvement.

**Comment by hadley** [comment]
With azure pipelines, it looks like you can set an env var for a single run. (Otherwise for travis, you'd change the env var in the settings, rebuild, and then change back again)

**Comment by jennybc** [comment]
We seem to be in a relatively happy place now.
