### ISSUE TITLE
Modify recommendation for closed source packages

### ISSUE THREAD

**Issue by jimhester** [hadley/r-pkgs#605]
@atheriel argues (IMHO) convincingly in [Copyright in Closed-Source R Packages](https://unconj.ca/blog/copyright-in-closed-source-r-packages-the-right-way.html) that the best way to license closed source packages is

> Copyright 2019 Widgets Incorporated. All rights reserved.

Which I think makes sense and suggest we should suggest this instead of 

https://github.com/hadley/r-pkgs/blob/1c6b34eb1900c3b348aa92d5923216cf61f23980/metadata.Rmd#L285

**Comment by hadley** [comment]
We should also add an equivalent function to use this.

**Comment by jennybc** [comment]
The usethis part has now happened in https://github.com/r-lib/usethis/commit/77d96f89fd22b1a7d1af5a3f6873eb8943ed32bb.

@Hadley you should be able to polish this off easily in your current work on the license chapter.

**Comment by hadley** [comment]
Yeah, and in fact this is already done 😄

**Comment by atheriel** [comment]
I'll probably add a note to the post when these are published/released. Thanks for the citation!
