### ISSUE TITLE
Xcode command line tools

### ISSUE THREAD

**Issue by behrman** [hadley/r-pkgs#607]
R build toolchain > macOS gives an alternative of downloading Xcode from the Mac App Store. I don't believe the current Xcode from the App Store includes the command line tools. I believe that they still need to be downloaded separately.

**Comment by jennybc** [comment]
Thanks @behrman. Can you point to any resources where I could verify that this is the current reality? Short of trying it myself?

**Comment by behrman** [comment]
@jennybc, On the [Xcode features page](https://developer.apple.com/xcode/features/), command line tools are listed under "Other tools included in macOS" with a link to a downloads page.

**Comment by jennybc** [comment]
@kevinushey this now feels like it echoes something implicit in something you've said recently. That Xcode and (?Xcode?) command line tools are separate? Any thoughts / details?

**Comment by kevinushey** [comment]
That's correct. If you download Xcode from the App Store, you'll get Xcode, which includes its own compiler toolchain. However, that is separate from the de-facto "command line tools" that can be downloaded separately and used by R or other applications.

The easiest way to install command line tools (from the command line) is:

```
sudo xcode-select --install
```

One other thing to note: macOS system utilities (e.g. `/usr/bin/git`) are smart enough to find either the version of Git provided by Xcode, or those provided by command line tools. As long as one of those is available and installed, `/usr/bin/git` will work. For example, I have Xcode installed, so:

```
$ xcrun --find git
/Applications/Xcode.app/Contents/Developer/usr/bin/git
```

But there is another "command line tools" version of Git on my system, as well:

```
/Library/Developer/CommandLineTools/usr/bin/git
```

But, in the context of R packages, installing only Xcode itself is insufficient -- command line tools must be installed, and those are provided separately.

**Comment by behrman** [comment]
@jennybc, I just tried removing my command line tools and running

    xcode-select --install

I was not prompted for a password. So an Apple developer account may be unnecessary.

**Comment by jennybc** [comment]
OK thanks to you both. It sounds like the landscape has changed since we originally wrote this section, so I will revise to reflect current reality.

**Comment by jennybc** [comment]
I am pretty sure the current content of the macOS section of the setup chapter reflects my most recent experiences.
