### ISSUE TITLE
Why doesn't ggplot2 Depend on scales?

### ISSUE THREAD

**Issue by Zedseayou** [hadley/r-pkgs#608]
Perhaps a minor issue, but this line in the "Namespace" section of the book has always puzzled me because it doesn't explain why ggplot2 doesn't `Depend` on scales.

>Similarly, ggplot2 should really Depend on scales, rather than Importing it.

I think this paragraph mentions why you generally shouldn't use `Depends` (minimizes changes to the global environment) but then seems to suggest that a package that cannot work without attaching a different package is the exception, and then cites `ggplot2` and `scales` as an example of this. I think there's two questions:

1. Should `ggplot2` `Depend` on `scales`? Basically, is `ggplot2` actually a good example of "a package designed to be used with another package"? Most users don't attach `scales` when using `ggplot2` after all, which might make it seem that it's not absolutely critical. If it is, is there some unique reason why it nevertheless doesn't `Depend` on `scales`, perhaps a historical one or because this would be too much of a breaking change?

2. What should this section say about the two packages? This depends on the answer to the first question, but I think that if it is a good example of the exception then the reason why it still doesn't Depend should be explained. If it isn't a good example, then it shouldn't be mentioned here because it's confusing.

I got here because I'm trying to write a helper package that will lose significant functionality if a different package is not attached when using it, and am thinking that I should use `Depends` instead of `Imports`.

**Comment by hadley** [comment]
Yeah, it's not clear today's Hadley would agree with that statement; I think scales is fine as imports. However, we could change this to a discussion of why devtools `Depend`s on usethis. But that's mostly an issue of backward compatibility and how to move a large number of functions from one package to another. So that's likely to be a more nuanced discussion than what the book needs.

**Comment by jennybc** [comment]
I think usethis and devtools should be the new poster children here. I.e. an actual case where we are currently using Depends.

**Comment by jennybc** [comment]
scales / ggplot2 is no longer mentioned here. We now use censored / parsnip / survival, devtools / usethis, and ggforce / ggplot2, in various places.
