### ISSUE TITLE
Make sure description of devtools::check() is accurate re: NOT_CRAN

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#612]
~`devtools::check()` does NOT in fact set `NOT_CRAN`. Some of the most common ways of running `devtools::check()` do set `NOT_CRAN=true`: namely, the RStudio Build pane and r-travis. But NOT_CRAN will not be set for a call to `devtools::check()` in the Console, unless the user has made explicit effort to do so.~

https://github.com/r-lib/devtools/issues/2135

~Rewording is needed in this vicinity:~

https://github.com/hadley/r-pkgs/blob/1c6b34eb1900c3b348aa92d5923216cf61f23980/check.Rmd#L25

**Comment by jimhester** [comment]
Actually after https://github.com/r-lib/devtools/commit/466300413f87e51abc5b3b4fa86eb859989450cc `devtools::check()` will set `NOT_CRAN` now. If we want I can do a devtools release before rstudio::conf with this change.

**Comment by jennybc** [comment]
OK great @jimhester. I'll leave the release timing to you, but it's clear that the wording in R Packages is faithful to devtools past and current intent and, in due course, the next devtools release.
