### ISSUE TITLE
data generated from `data-raw` is invisible for users

### ISSUE THREAD

**Issue by kongdd** [hadley/r-pkgs#613]
Help!
I used `data-raw` in my package and documented them in `R/data.R`. But those data are invisible for users. 
Am I missing something important?

Cheers, 
Dongdong

**Comment by jennybc** [comment]
Yes, the `data-raw/` directory is just a suggested convention for where to put the *code that generates* datasets you ship with your package. It is expected that any such data preparation script still uses, for example, `usethis::use_data()` to *save the actual data* in various ways that make it available in the package. The default is `internal = FALSE`, which saves a data object that's meant to be visible to users. 

I recommend reading the help for `usethis::use_data()` and poking around `data-raw/` in a few data packages like babynames, gapminder, and repurrrsive.
