### ISSUE TITLE
Provide advice on how to handle raw data that is large

### ISSUE THREAD

**Issue by williamlief** [hadley/r-pkgs#618]
The section on [Exported Data](https://r-pkgs.org/data.html#data-data) recommends including the raw data and code in `data-raw/`, and adding `data-raw/` to `.Rbuildignore`. 

I have done so and have my entire project as one github repository. In my case the raw data is ~170 mb (the clean data is < 1 mb), and while `data-raw/` is not included when the package is built, it is unfortunately downloaded by `devtools::install_github`*. This causes the install to take several minutes to execute. This is not ideal behavior, and I was wondering if you had any suggestions for a better approach. I don’t want people interested in my data wondering what is wrong with my package that is causing it to take so long to download. 

Can the section on including raw data and cleaning code include a discussion of this problem and suggested solutions for projects with larger raw data sets?

*see also here: https://community.rstudio.com/t/how-to-exclude-a-folder-to-be-downloaded-when-hosting-r-package-in-github/4625

**Comment by jennybc** [comment]
`install_github()` simply grabs a repo as a ZIP archive. There is no way for it to be more selective.

170 MB is an awkward file size for a Git(Hub) repo, in general. I'm surprised you managed to do this, since GitHub's docs say:

> In addition, we place a strict maximum size limit of 100 MB for individual files in a repository.

<https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota#file-and-repository-size-limitations>

A raw dataset of this size probably needs to NOT be tracked in the git repo for your package.

**Comment by williamlief** [comment]
Thanks for confirming that `install_github()` cannot be selective. 

To be clearer, here are the generalized questions / scenario / goals:

- Many raw files that are individually smallish (~2-10 MB), but collectively large
- Necessity of allowing end users to inspect raw data and cleaning code for accuracy in final product
- Value in tracking when new raw files are added/removed, or changes to raw files even without line diffs for binary formats (`.xlsx`, `.pdf`)
- Wanting to use r-package documentation for the final clean data
- Keeping clean data and raw data together for development and maintenance

It seems like if I don't want to have very long install times for the clean-data the best solution will be to create two repositories, one as a plain directory structure with the raw-data and cleaning scripts, and another that contains the package with the clean data and documentation. I'll then need to document the link to the raw-data repo in the clean-data repo and manually update the clean-data repo when I have data updates / fixes implemented in the raw-data repo. 

But I welcome other suggestions and think that this would be valuable information to include in the next edition's data section.

**Comment by jennybc** [comment]
> the best solution will be to create two repositories, one as a plain directory structure with the raw-data and cleaning scripts, and another that contains the package with the clean data and documentation

I think just getting the raw data files out of the main package repo is enough (so, yes, in a second repo). But I would still leave the cleaning scripts in the main package.

**Comment by jennybc** [comment]
I think this topic is not quite broadly applicable enough for us to develop it in R Packages. Also, it's not something we've got a lot of experience with, which I tend to honour as the indicator that something may be important, but the world needs to hear from someone else about it, who has more experience. Thanks for raising this issue.
