### ISSUE TITLE
Building vignettes with dev package version

### ISSUE THREAD

**Issue by cderv** [hadley/r-pkgs#619]
This is related to this issue https://github.com/r-lib/devtools/issues/2181 from experience at tidydevday in SF. 

Chapter 9 on vignettes explains that the development cycle is to write the vignette, run chunk by chunk then run all using Knit button. I think something could be added regarding the package version used. 

By default, vignettes contain `library(<pkg>)` and knitting will run them using the version of 📦 inside the library, and not the current dev version (that may have been loaded with `load_all()`)
`devtools::build_vignettes` has `install = TRUE` to deal with that by rendering vignettes using a temp library path in which the current dev version is installed. 

Adding some explanations and advices on this in the book could help new developers.

**Comment by jennybc** [comment]
The world has changed for the better since this issue was opened:

* `devtools::build_rmd()` is a generally useful tool for this problem, with `build_readme()` being a specialized variant.
* pkgdown facilitates looking at one's rendered vignettes.

**Comment by hadley** [comment]
Related: https://github.com/r-lib/devtools/issues/2203

Alternatively we might consider seeing if the IDE team could build this in.
