### ISSUE TITLE
Vignette template doesn't have author

### ISSUE THREAD

**Issue by angela-li** [hadley/r-pkgs#621]
The vignette template provided by usethis no longer has the author/date parameter included, but the text in the Vignettes chapter still mentions the [author/date](https://github.com/hadley/r-pkgs/blob/1c6b34eb1900c3b348aa92d5923216cf61f23980/vignettes.Rmd#L83) in the YAML header. Thoughts on adding this to the usethis template?

**Comment by jennybc** [comment]
It is an intentional omission in the usethis template, because we generally don't want author/date in vignettes. I feel like that has been written down somewhere, but I sure can't find at this moment. The mismatch is because I haven't revised that chapter yet.

**Comment by angela-li** [comment]
Ok, I figured the text hadn't been revised yet! I was recently asked to add an author field to a vignette I contributed to learnr, but I guess that's specifically in the case where the vignette is contributed by someone who isn't the package author. Thanks!

**Comment by jennybc** [comment]
Yeah when I say "we" I mean the tidyverse team. Even we are not completely uniform in our habits, but you'll see even more differences with, e.g., other folks within RStudio. But I do believe the omission in the template is intentional.
