### ISSUE TITLE
Whole Game chapter: add summary at end of R functions used in console

### ISSUE THREAD

**Issue by SamEdwardes** [hadley/r-pkgs#622]
I just finished interactively going through [Chapter 2: The Whole Game](https://r-pkgs.org/whole-game.html). I found it very helpful, thank you for creating! 

I want to suggest that it may be useful for readers to summarize all of the functions used in the console at the end of the chapter. When starting out it can be tricky to keep track of the `devtools` and `usethis` functions that you need to call on a regular basis.

For example, the summary could look something like this.

> You have now build your first R package. As a reminder here are the functions you will use on a regular basis.
>
> ```R
> devtools::create_package("~/path/to/foofactors") # creates a template for new R package
> usethis::use_git() # adds git boilerplate
> usethis::use_r("fbind") # create a new file in R directory
> ...
>```

**Comment by hadley** [comment]
I think that's the job of the cheatsheet (which needs to be updated)

**Comment by SamEdwardes** [comment]
Thank you for the response Hadley. Assuming this is the cheatsheet?

https://github.com/rstudio/cheatsheets/raw/master/package-development.pdf

**Comment by jennybc** [comment]
The cheatsheet definitely needs updating, but I think a concluding "functions used here" might still be a good addition to the Whole Game.

Maybe in some sort of table that is also indicates rough categories of usage, e.g. "run this once per package" for `create_package()` or `use_git()` vs. "run this to add stuff to your package" for `use_package()` vs. "run this often during development" for `load_all()` or `document()` or `test()`.
