### ISSUE TITLE
Old website should contain note that never version is available

### ISSUE THREAD

**Issue by lorenzwalthert** [hadley/r-pkgs#632]
I think it would make sense to add a note to the old version of the r-pkgs website (http://r-pkgs.had.co.nz) that this page is outdated and add a link to the new version. Because it still shows up higher in duckduckgo and google when I search "r packages book" so people who don't know about the new version will find the old one. 
![Screenshot 2020-04-25 at 18 36 44](https://user-images.githubusercontent.com/10477073/80286954-dc26d800-872e-11ea-9bda-1ad2fcf37afc.png)

**Comment by jennybc** [comment]
I think that might have to be a @Hadley task. And it's possibly that it's hard to do, i.e. that the old website is a bit hard to tinker with at this point. But I agree it's a good idea in principle.

**Comment by julianstanley** [comment]
Might be easiest to just to remove the old material entirely and redirect from http://r-pkgs.had.co.nz/ to https://r-pkgs.org, if hadley is willing. 

(I'm in this repo now because I was following directions on http://r-pkgs.had.co.nz/, saw a depreciated code snippet, went to go fix/pull request, but then noticed it was already fixed on the updated site, which I wasn't aware of until now. So a redirect may save time for people like me in the future)

**Comment by jennybc** [comment]
@Hadley do you have any thoughts on this?

I think there might be one answer *during* the revision phase and another once it's (substantially) complete.

**Comment by hadley** [comment]
Just that it's a lot of work to update the old site, so I'd prefer to only do it once.

**Comment by jennybc** [comment]
In that case, I think it would be good to put some sort of notice in, alerting people to the development of a 2nd edition.

Is that something I can help with or is it easier for you to do?

**Comment by hadley** [comment]
Do we believe that the chapters are going to remain constant? i.e. should we label each old chapter with a link to the equivalent new chapter, or just to the new book?

But maybe, unlike Advanced R where the content and organisation changed significantly, there's no reason to keep two versions alive on the web and we should just redirect the old to the new? That is likely to be easier.

**Comment by jennybc** [comment]
I could definitely create and maintain a map between chapters of the 1ed and where it should redirect in the 2ed.

My only experience with this is such a table for STAT 545:
https://github.com/rstudio-education/stat545/blob/master/_redirects

But I suspect we are dealing with different technology re: the old site?

**Comment by hadley** [comment]
I could just do a global redirect from `http://r-pkgs.had.co.nz/*` to `http://r-pkgs.org/*` and then we could use netlify redirects for any pages that have changed.

**Comment by jennybc** [comment]
Yeah that works.

**Comment by hadley** [comment]
Redirect now active
