### ISSUE TITLE
[cph] seems mandatory now as does @return

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/r-pkgs#635]
https://github.com/hadley/r-pkgs/blob/master/metadata.Rmd#L246-L247 indicates `[cph]` is to identify non-author copyright but it seems that there's a new unwritten CRAN rule that it needs to be there for the author.

Also, https://github.com/hadley/r-pkgs/blob/721b7888bde84aab6832dd9596e762957022e821/man.Rmd#L226-L229 suggests `@return` is optional but that is def no longer the case.

I can PR in changes if desired.

**Comment by hadley** [comment]
It's slightly tricky since these are only required for initial submissions (i.e. the ones that get the human check). We should definitely update the language, but I'm not sure how much of the nuance we need to convey to the reader.

**Comment by hrbrmstr** [comment]
I had, literally, the exact same thoughts :-)

After getting the CRAN note I jotted back to the online version of the book
(also: 2015! 5 years since 1st ed! #timeflies) to see if other, new,
kinda-undocumented CRAN guidelines/requirements were in there since this is
the de-facto best ref.

I'll ponder some things and toss a few drafts to banter on.

**Comment by DavisVaughan** [comment]
@hrbrmstr if you want to contribute to a growing list of these ad-hoc checks in a less formalized way than the book, you can add them as issues here https://github.com/DavisVaughan/extrachecks

(both of the ones you mentioned are there already)

**Comment by hadley** [comment]
(Note to self + Jenny: we should just provide a discussion about the general nature of the additional manual checks performed on first submission and then link to extrachecks for details).

**Comment by jennybc** [comment]
The updated metadata chapter (DESCRIPTION, basically) already has new content on `cph`.  The rest of this stuff will get reworked as the relevant chapters get revised, e.g. `@return` in documentation chapter and the whole extra checks business in expanded coverage of release / package lifecycle. I am labelling this accordingly.

**Comment by hadley** [comment]
I've now mentioned that `@returns` and `@examples` are now effectively required in the docs chapter.
