### ISSUE TITLE
Vignette metadata entry typo?

### ISSUE THREAD

**Issue by royfrancis** [hadley/r-pkgs#638]
On this page http://r-pkgs.had.co.nz/vignettes.html under metadata, this code block:

```
---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```

Should `\usepackage[utf8]{inputenc}` have preceding `%`? This https://github.com/r-lib/devtools/issues/587#issuecomment-56053598 comment has a `%` in it.

**Comment by hadley** [comment]
I'm pretty sure it should now be `%\VignetteEncoding{UTF-8}`; at least that's what `usethis::use_vignette()` generates.
