### ISSUE TITLE
Testing chapter says to use `context()` at the top of files

### ISSUE THREAD

**Issue by KatherineCox** [hadley/r-pkgs#642]
https://github.com/hadley/r-pkgs/blob/406b69cabd502c4d7e806740e878363807237c7b/testing.Rmd#L396

But the `context()` documentation says:

> Use of context() is no longer recommend. Instead omit it, and messages will use the name of the file instead. This ensures that the context and test file name are always in sync.

**Comment by jennybc** [comment]
Yes this chapter has not gotten its refresh yet.
