### ISSUE TITLE
Mention R-package-devel mailing list

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#645]
https://stat.ethz.ch/mailman/listinfo/r-package-devel

Searchable here:

https://www.mail-archive.com/r-package-devel@r-project.org/

**Comment by jennybc** [comment]
This probably belongs with "package lifecycle" content, under a general banner of how to solve one's own ongoing package development problems, how to keep learning more, etc.

**Comment by hadley** [comment]
Could also go in the intro, or wherever we mention R-exts etc.
