### ISSUE TITLE
Data chapter should address encoding

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#646]
Although the OP eventually decided that his fix did work, this still is a good concrete example to use as inspiration for thinking about the encoding of data embedded in a package:

https://www.mail-archive.com/r-package-devel@r-project.org/msg04962.html

We already address the companion issue in the "code" chapter about `R/`, i.e. how to eliminate non-ASCII characters in source.

**Comment by jennybc** [comment]
Talk about this NOTE:

```
*Note: found 1234 marked UTF-8 strings*
```

**Comment by jennybc** [comment]
Relevant thread:

https://stat.ethz.ch/pipermail/r-package-devel/2019q3/004243.html

**Comment by hadley** [comment]
We should double check that this is still a problem; I don't remember seeing it recently.
