### ISSUE TITLE
How to package and document active bindings ?

### ISSUE THREAD

**Issue by moodymudskipper** [hadley/r-pkgs#651]
I've found the following ressource showing how to add an active binding to one's package : 

https://stackoverflow.com/questions/54204187/use-makeactivebinding-inside-a-package

It works ok but triggers CMD check warnings because for some reason it seems the active binding are run (and in my case fail in this context).

Another thing that isn't obvious is how to document these active bindings, either alone or in another function's help file (so that `?my_active_binding` leads there.

I'd be happy to see this sorted out in a section of your book!

**Comment by hadley** [comment]
I don't think you should be routinely add active bindings to your package, and it's certainly too advanced for this book.
