### ISSUE TITLE
Shiny, learnr, tutorial pane

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#655]
Do we have advice on shipping Shiny apps in or as a package? What about learnr? The tutorial pane of RStudio IDE?

**Comment by sibyllwangxxxx** [comment]
In my work, I package a Shiny App by putting all module functions, ui.R, server.R and global.R in /R. Examples of individual modules and the overall app in subfolders in /inst. The perks of this is, on Shiny Server Pro, the module example apps and overall app are conveniently deployed with a path identical to the folder structure.

**Comment by jennybc** [comment]
Similar to #958.

And, even though this issue has been open longer, this basically applies: These are all interesting questions, but I doubt we're going to take a position on these in the second edition which is in "necessary changes only" mode. Once we get it into the formal publication process, we can re-open our minds to matters like this, as the online version of the book is an evolving document.
