### ISSUE TITLE
`MarkdownWrap: Sentence` in r-pkgs.Rproj

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#660]
@Hadley You introduced this change to `r-pkgs.Rproj`:

<img width="952" alt="Screen Shot 2020-09-12 at 8 15 34 AM" src="https://user-images.githubusercontent.com/599454/92998694-289d6500-f4d0-11ea-8bab-d2e9f572d2bd.png">

However, for anyone who does not use the dailies or, I guess more specifically, does not use a version of the IDE that supports this, it is constantly being deleted by the IDE. Therefore I always see this as a diff and am trying to remember to discard the deletion and not stage/commit it. But one day I will slip up.

One of us needs to do `git update-index --assume-unchanged r-pkgs.Rproj` and I'm going to propose that it should be you 😇. So, specifically, revert 4875935a29d40a85e0a78acb49c11d933b7bd5cf and then do `git update-index --assume-unchanged r-pkgs.Rproj`.

**Comment by jjallaire** [comment]
That's unfortunately always been how it works when older versions of the IDE see a project file setting they don't know about.

It doesn't come up that often b/c we rarely add project-level settings (and then even when we do users rarely set them).

For this release though I added a bunch of them related to markdown output from visual mode which are more likely to get used, so this annoyance will probably persist until v1.4 is more widely used (note that we have a more stable preview release of v1.4 coming in a week or two).

**Comment by jennybc** [comment]
This has self-resolved.
