### ISSUE TITLE
Still 1 note after second run of "check" in toy example

### ISSUE THREAD

**Issue by SheridanLGrant** [hadley/r-pkgs#663]
https://github.com/hadley/r-pkgs/blob/4ddb49649764f9dc335bf554ddf2fc6065e8be9b/Whole-game.Rmd#L474

**Comment by jennybc** [comment]
(It would be helpful to show what you mean.)

```
#> ❯ checking for future file timestamps ... NOTE
#>   unable to verify current time
```

This is a problem with R itself right now, where they have rigged it to check the time via an API and the targetted site is down.
