### ISSUE TITLE
Consider including a chapter or section on logging?

### ISSUE THREAD

**Issue by alexpghayes** [hadley/r-pkgs#664]
I suspect that logging is outside the scope of this book, but want to bring it up as a possible topic. To my knowledge, at the moment there are few resources explaining how or why to log in R, despite the fact that logging can be incredibly useful when implementing/debugging numerical algorithms!

**Comment by hadley** [comment]
Yeah, logging feels mostly orthogonal to packaging to me. I think it’s more about unattended code.
