### ISSUE TITLE
6.5 tribble call not qualified in code example?

### ISSUE THREAD

**Issue by Lenostatos** [hadley/r-pkgs#672]
Hello,

in chapter 6.5 (The package within -> Echo: a working package) this sentence:
https://github.com/hadley/r-pkgs/blob/ec6efe1524f1c12075cfd8786ddfbf9cd4fcd1ba/Package-within.Rmd#L437
states that all calls to tidyverse functions have been qualified. However, the code example a few lines above that this refers to contains a call to the `tribble()` function in the first line without qualification. Maybe I'm missing something here, but it looks to me as if this was not intended.

Cheers, Leon

I assign the copyright of this contribution to Hadley Wickham.

**Comment by jennybc** [comment]
Yes, I agree. Would you like to make a pull request to fix, i.e. make it `dplyr::tribble()`? (FYI, `tribble()` really comes from tibble but dplyr re-exports it and I think namespacing with dplyr is the right thing to do in this simple example).

**Comment by Lenostatos** [comment]
Sure, is #673 okay?
