### ISSUE TITLE
Oversized screenshots on retina display

### ISSUE THREAD

**Issue by klmr** [hadley/r-pkgs#683]
Some of the screenshots included in the book are shown as oversized.

For instance, [the chapter on *Git*](https://r-pkgs.org/git.html) includes several screenshots that are cut off due to being too large (the meta-screenshot below was taken on a 2× DPI retina display, but the same is true on other displays). By contrast, the [*Workflows 101* chapter](https://r-pkgs.org/workflows101.html) displays correctly-scaled screenshots, even though these are also apparently retina display screenshots (as can be seen when opening them in a separate tab, e.g. [`project-options-2.png`](../master/images/project-options-2.png). Looking at the source code, the “correct” images use scaling but no DPI:

https://github.com/hadley/r-pkgs/blob/b5badb8449e94c549c985aa726b99d7740c92250/Workflow101.Rmd#L252-L254

… whereas the “incorrect” images specify a DPI but no scaling:

https://github.com/hadley/r-pkgs/blob/b5badb8449e94c549c985aa726b99d7740c92250/git.Rmd#L101-L103

Meta-screenshot (just in case the problem is device dependent):

![Screenshot 2020-12-17 at 09 48 56](https://user-images.githubusercontent.com/38931/102471431-1b52c200-404d-11eb-82e0-5081d825106d.png)

**Comment by jennybc** [comment]
Luckily this Git material is likely to go away or at least be abbreviated / refreshed. The screenshots that are behaving correctly are the in material that's already been revised. So I suspect this is going to self-resolve.

**Comment by jennybc** [comment]
I'm going to assume that all screenshots will get refreshed and this is going to take care itself.
