### ISSUE TITLE
Update Chapter 12 on expect_equal_to

### ISSUE THREAD

**Issue by XiaoqiLu** [hadley/r-pkgs#693]
In case this is not on your TODO list:

the recent update "`expect_known_output()`, `expect_known_value()`, `expect_known_hash()`, and `expect_equal_to_reference()` are all deprecated in favour of `expect_snapshot_output()` and `expect_snapshot_value()`." makes Chapter 12 on "expect_equal_to_reference()" outdated

**Comment by jennybc** [comment]
This will definitely take care of itself when that chapter gets revised. Thanks.
