### ISSUE TITLE
Consider workflow diagrams

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#698]
<img width="967" alt="Screenshot 2021-03-07 at 8 31 08 AM" src="https://user-images.githubusercontent.com/4196/110243330-78a93180-7f1f-11eb-9c4f-2fc665fd6675.png">

<img width="1067" alt="Screenshot 2021-03-07 at 8 31 24 AM" src="https://user-images.githubusercontent.com/4196/110243334-819a0300-7f1f-11eb-98d5-28a279075650.png">

etc

[diagrams.zip](https://github.com/hadley/r-pkgs/files/6097294/diagrams.zip)

**Comment by kalaschnik** [comment]
I am digging through the entire book as I am creating my very first R package (love the book, and the tools you people created to streamline the entire process is just awsome DX ❤️) — and along the journey, I am creating a visualization of the main workflow stages. This is primarily for (future) me and other colleagues. This is the progress as of today but this changes almost on a daily basis, as I am still reading and revisit some chapters:

Notes:
- Package names are on purpose visible to show where functions come from
- I am thinking about how to best integrate git and testthat in the visualization without bloating it too much
- That entire thing will be in the size of A3 or A2 in the end
- I am working in draw.io/diagrams and I am happy to share a link once this is more mature (content-wise and visually)

![image](https://user-images.githubusercontent.com/9831678/151149079-8eb36b00-d8ef-40c5-93e8-befb4ccc5a1f.png)

**Comment by kalaschnik** [comment]
Is there a tidyverse style guide (not for code, one for your corporate colors and typefaces)? I would be happy incorporating your figures in my figure and work towards a tidyverse look.

**Comment by jennybc** [comment]
> Is there a tidyverse style guide (not for code, one for your corporate colors and typefaces)?

No, not really. I suppose certain aesthetic preferences are implicit in https://github.com/tidyverse/tidytemplate, which is where our pkgdown template lives.

Please do keep us posted on how your diagram efforts progress!

**Comment by hadley** [comment]
Reminder to us that we brainstormed a new workflow diagram for the cheatsheet and we should bring it back here.

**Comment by jennybc** [comment]
https://github.com/rstudio/cheatsheets/blob/main/keynotes/package-development.key

https://github.com/rstudio/cheatsheets/blob/main/package-development.pdf

**Comment by jennybc** [comment]
The action item here remains to port over the new workflow diagram that's in the cheatsheet.

**Comment by jennybc** [comment]
I have added that workflow diagram to the Whole Game chapter.
