### ISSUE TITLE
Add discussion of use_pipe

### ISSUE THREAD

**Issue by iangow** [hadley/r-pkgs#705]
I discovered `use_pipe` [here](https://stackoverflow.com/questions/27947344/r-use-magrittr-pipe-operator-in-self-written-package/27979637#27979637). Awesome.

Would a discussion of this have a home in "R Packages"?

**Comment by jennybc** [comment]
I think might be rather specific. But, depending on how various chapters, evolve, maybe it could be worked in. It is definitely a good example of something one might import and, optionally, export, that is not a simple function.

**Comment by hadley** [comment]
I think we can now drop this, since we no longer broadly recommend `use_pipe()`; just use the base pipe.
