### ISSUE TITLE
Replacing `fbind` with another example

### ISSUE THREAD

**Issue by reikookamoto** [hadley/r-pkgs#709]
According to [this blog post](https://www.r-bloggers.com/2021/05/new-features-in-r-4-1-0/), one of the new features of R 4.1.0 is that combining two factors now results in another factor instead of an integer vector.

Chapter 2 of this e-book involves creating and packaging a function called `fbind()` which deals with what happens when you tried to concatenate two factors prior this latest major release (outlined in [2.6](https://r-pkgs.org/whole-game.html#write-the-first-function)). Since this behaviour won't be replicated for those following along the book on R >=4.1.0, I think this particular "case study" should be updated.

Sorry if this is already being taken care of by the authors.

I assign the copyright of this contribution to Hadley Wickham.

**Comment by jennybc** [comment]
Yes, this had occurred to me and I even thought I'd opened an issue about it, but it looks like I did not. So this is a good issue to register.

I'm open to suggestions of what to replace `fbind()` with in that case study.

It needs to be a super small, simple function that works around a little hangnail that people encounter often in R.

One thing that comes to mind is `strsplit1()`, which would just be `strsplit(x, split = "/")[[1]]` (with a check for scalar input). Or, generally, I think the regular expression functions are probably a good place to look.

**Comment by reikookamoto** [comment]
I think I've actually encountered that issue with `strsplit()` myself!

Were you looking for an example that involves factors to keep in line with the name of the toy package (`foofactors`)? Or are you open to other suggestions?

**Comment by jennybc** [comment]
No, I have zero attachment to a factors-based example. It's just what I came up with at the time.

**Comment by MrFlick** [comment]
Another suggestion might be:

```
exact_match <- function(string, substring) {
  grepl(substring, string, fixed=TRUE)
}

grepl(".com", c("hello.com", "income.org", "test.net"))
# [1]  TRUE  TRUE FALSE
exact_match(c("hello.com", "income.org", "test.net"), ".com")
# [1]  TRUE FALSE FALSE
```

By default people might not expect that certain characters have special meaning in regular expressions. You could offer an alternative that assumes fixed strings by default. It also changes the argument order to be more pipeable.

**Comment by debiatan** [comment]
I've just come across this issue while reading the book, which has already been compiled with a version of R that doesn't exhibit the factors issue. The text of the book doesn't show the integer values, which makes for a confusing read. While the issue is not resolved, it might make sense to add a simple note pointing out the example is outdated and listing the old behavior:
```
> c(a, b)
[1] 1 3 4 2 1 3 4 2
```

**Comment by turbanisch** [comment]
Another idea: `%in%` is not equivalent to multiple OR statements (which is how it is explained in R4DS) when it comes to missing values. Even though this is not necessarily an "inconsistency" (as I phrased it on [stackoverflow](https://stackoverflow.com/q/68558394/10363163)) it might be a good application in a dummy package.
