### ISSUE TITLE
Consider adding warning re inst/doc to inst.Rmd

### ISSUE THREAD

**Issue by eeholmes** [hadley/r-pkgs#724]
In the chapter on the inst folder, the user is warned about avoiding certain subfolder names, such as inst/inst. A warning should also IMO be added about the name inst/doc.  inst/doc is deleted by `pkgbuild::build()` in a variety of situations like running check() from RStudio and potentially `remotes::install_github()`.  I believe users are advised not to use inst/doc for non-vignette documentation, but they are not warned that **pkgbuild** will automatically delete this folder (at least in non-interactive mode).

**Comment by hadley** [comment]
This is a fairly esoteric concern so I don't think we need to mention it in the book. Additionally, `pkgbuild::build()` now asks before deleting so it shouldn't be a surprise.
