### ISSUE TITLE
Section 20.8: r-packages Mailing List Do Not Accept Rmd For New Release

### ISSUE THREAD

**Issue by drag05** [hadley/r-pkgs#726]
I have published a new package on CRAN and submitted a new release announcement using Rmd file as suggested in this section. 

Their answer was:
```
"Your message was deemed inappropriate by the moderator. Please write
a few lines of regular test yourself about your package, including the
CRAN link  not copy-paste of rmarkdown.."

Any questions or comments should be directed to the list administrator
at:

    r-packages-owner@r-project.org"
```
I haven't actually copy/pasted the Rmd, just attached it to the email.

Thank you!

**Comment by hadley** [comment]
Link to section: https://r-pkgs.org/release.html#promotion

I think the advice should be to send the render md to the mailing list, not the .Rmd.

**Comment by drag05** [comment]
@hadley 

The response from `r-packages mailing list` seems clear although, it mentions "regular test" which I am interpreting as "regular text":
```
Please write a few lines of regular test [sic] yourself about your package, including the
CRAN link  not copy-paste of rmarkdown.."
```
According to this, just writing a few lines about the package and inserting the CRAN link should be sufficient. I have done exactly that in my response email and I am waiting for mailer's second reply.

Thank you!

**Comment by drag05** [comment]
The mailer accepted the announcement as few lines of text. 
Given the multiple `output_format` options of `rmarkdown::render()` function, it would probably be worth changing the wording from "This should be an R Markdown document that..." to " as release announcement, paste the content of your md into the body of the email...".
Thank you!
