### ISSUE TITLE
Instructions for avoiding 'abort' calls

### ISSUE THREAD

**Issue by ms609** [hadley/r-pkgs#728]
https://github.com/hadley/r-pkgs/blob/master/src.Rmd line 402 states:

> Instead, use `error()` which is equivalent to calling `stop()` in R.

But `error()` seems not to be a function available to C.  Is it possible to add some context to this line detailing, for example, which library `error()` is contained within? Or is the intention to suggest using, for example, `throw std::range_error()` or equivalent?

**Comment by hadley** [comment]
We're no longer including a compiled code chapter so this is now out of scope, sorry.
