### ISSUE TITLE
Tidyverse revdep process

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#735]
Notes for future inclusion somewhere in the book

---

# Revdep check

We use `revdepcheck::cloud_check()` to test our packages because it runs `R CMD check` massively in parallel, making it possible to run revdepchecks for packages like testthat (with >6,000 revdeps) in just a few hours. 

It doesn't always agree 100% with CRAN:

* False positives: sometimes it reports a package has broken but it's actually ok. This most commonly happens because of flaky tests that fail randomly, but sometimes happens because the instance runs out of disk space or other resources so the first check using the CRAN version succeeds and the second check using the GitHub version fails.

* False negatives: main source of false negatives is packages that `cloud_check()` can't test because fail to install, typically because some system requirements (e.g. java) is missing. These are separately reported as "failed to test" but are still included in `problems.md` because it's also possible to create an install failure by (e.g.) removing an exported function that's imported by another package.

Generally these differences are less of a worry now that CRAN's own revdep checks are well automated so new failures typically don't involve a human.

# Breaking changes

If the revdepcheck reveals breakages, it's good practice to work through each failure to determine if it's:

* A false positive (i.e. obviously not related to your package, or clearly shows failing HTTP request).

* A bug that you need a fix.

* A non-breaking change, i.e. a failure caused by off-label usage of your code.

* A deliberate breaking change.

If your update will break another package (regardless of why), you need to inform the author so they hear it first from you, rather than CRAN. The nicest way to do so is with a PR that fixes the change. This can be a decent amount of work, but I think it's generally good practice because it forces you to confront the pain that a breaking change causes. If you decide to do this, make a new checklist in the release issue that lists all the packages that you need to fix. As you create the PRs add them, and check them off when they're merged. You should let the authors know when you plan to submit to CRAN (so they can submit before that), but their  submission is up to them - you can submit to CRAN knowing that you've done your due diligence (and if you explain to CRAN that your provided patches, they will accept it, even if it breaks some packages).

If your update breaks so many packages that this is infeasible to provide PRs for all of them, you need to consider the severity of the breakage and the benefit of the change, and seriously reconsider whether you want to make this change. If it affects that many packages, it's likely to affect even more user-facing code. If you still decide to go ahead (presumably because the change is _really_ compelling), you can use `revdepcheck::cloud_email()` to notify authors en masse. Make sure the email includes a link that describes the most common breaking changes and how to fix them.

**Comment by jennybc** [comment]
Adding some details that come to mind ...

> It doesn't always agree 100% with CRAN:
> 
> False positives: sometimes it reports a package has broken but it's actually ok. This most commonly happens because of flaky tests that fail randomly, but sometimes happens because the instance runs out of disk space or other resources so the first check using the CRAN version succeeds and the second check using the GitHub version fails.

This also happens the other way around, i.e. where CRAN gets a false positive that we did not see, due to flaky tests (usually internet related, rate limits, etc.). In fact, it feels like, as long as flaky tests are out there, the sheer scope of our reverse dependencies mean that we're very likely to suffer from one.

Twice recently I have also gotten false positives due to changes in R-devel that affect a reverse dependency:

* optimall and incorrect usage of `all.equal()` mediated by `testthat::expect_equal()` https://github.com/yangjasp/optimall/issues/2 (detected via glue v1.6.1 submission)
* broom and `default.stringsAsFactors` https://github.com/tidymodels/broom/issues/1083 (detected via glue v1.6.2 submission)

> False negatives: main source of false negatives is packages that `cloud_check()` can't test because fail to install, typically because some system requirements (e.g. java) is missing. These are separately reported as "failed to test" but are still included in problems.md because it's also possible to create an install failure by (e.g.) removing an exported function that's imported by another package.

There's also a Bioconductor part of the story here.
