### ISSUE TITLE
LazyData should not be encouraged by default if there is no data/ directory 

### ISSUE THREAD

**Issue by daattali** [hadley/r-pkgs#737]
For many years, adding `LazyData: true` was safe in any package.

Recently CRAN checks started rejecting packages that have that field if they don't also have a `data/` directory. Specifically CRAN complains with: `'LazyData' is specified without a 'data' directory`

The book makes this recommendation [here](https://r-pkgs.org/description.html) which should be updated

**Comment by daattali** [comment]
Also mentioned in https://r-pkgs.org/data.html#data

**Comment by mbjones** [comment]
See also https://github.com/r-lib/usethis/issues/1403 which updated `usethis`.
