### ISSUE TITLE
Be more specific in Exported Data Chapter

### ISSUE THREAD

**Issue by MarceloRTonon** [hadley/r-pkgs#739]
In line 138 of [Chapter 14 Exported Data](https://github.com/hadley/r-pkgs/edit/master/data.Rmd), in the [14.5 CRAN notes](https://r-pkgs.org/data.html#data-cran) section, the following is said (bold added):

> Generally, package data should be smaller than a megabyte - if it’s larger you’ll need to argue for an exemption. This is usually easier to do if the data is in its own package and **won’t be updated frequently**.

What can be considered _not frequently updated_? Is an annual update justifiable? What can be given as parameter or a good rule of thumb?

**Comment by jennybc** [comment]
Probably the best way to handle this is indirectly. I.e. point to some data packages that successfully survive on CRAN. Aspiring data package authors can then look at whichever aspects that are relevant to their concerns (size, frequency of update, etc.).

I am loathe to directly vouch for any specifics that aren't actually advertised by CRAN itself.
