### ISSUE TITLE
May the testing chapter include visualization testing?

### ISSUE THREAD

**Issue by PursuitOfDataScience** [hadley/r-pkgs#758]
The testing chapter ([link](https://r-pkgs.org/tests.html)) is important, but scanning through it I found it never mentioned visualization testing. Maybe it is time to introduce some viz testing packages, such as [vdiffr](https://github.com/r-lib/vdiffr), in the next version of the book? Thanks.

**Comment by hadley** [comment]
Probably not as it's too specialised. There's an existing testthat issue to add a vignette about these more complicated situations.
