### ISSUE TITLE
Terminology in Git and GitHub chapter: use `main` or add reference in footnote

### ISSUE THREAD

**Issue by hanneoberman** [hadley/r-pkgs#767]
For most new Git/GitHub users (the target audience of this chapter) the default branch will be called `main` now, as opposed to `master`. It would be nice to change this throughout the chapter, or at least refer to the discussion, e.g. https://www.tidyverse.org/blog/2021/10/renaming-default-branch/.

**Comment by jennybc** [comment]
This entire chapter is basically on the chopping block for the 2nd edition, in favour of other resources, such as https://happygitwithr.com. Any remaining Git / GitHub content here will be very high-level (more about *why version control is good*) and certainly won't get into branch names. This will self-resolve shortly.
