### ISSUE TITLE
Add alt text to images

### ISSUE THREAD

**Issue by hanneoberman** [hadley/r-pkgs#768]
It may be a hassle, but it would be nice if you could add alt text to the in-line images. This would make the book more accessible to people who use screen readers. An example of such an image that could benefit is the Fork button in this section: https://r-pkgs.org/git.html#pr-make. You're probably well aware how to do this, but just in case: https://www.rstudio.com/blog/knitr-fig-alt/.

**Comment by jennybc** [comment]
Yes I agree this is a standard we should implement as we revise the book.

The specific image you're talking about is in a chapter that will probably be retired in favour of other resources.

But the point stands.
