### ISSUE TITLE
an explanation of "why" system.file() is necessary to access package files?

### ISSUE THREAD

**Issue by tanho63** [hadley/r-pkgs#776]
Hi! In chapter 16 it currently has a brief mention of using `system.file()` to access files included in inst/

> To find a file in inst/ from code use [system.file()](https://rdrr.io/r/base/system.file.html).

but I was trying to explain _why_ this was to someone and came up with the following explanation:

> okay, so what's happening here is that your package gets installed on the user's machine, right? system.file() builds a path to the user's package installation directory so that your function can reference it. your previous way would have been referring to the user's working directory and looking for "sql/export_file.sql" there.

I'm not sure if this is 100% the reason why but it seems to make sense to me - and thought it might be useful to include

**Comment by jennybc** [comment]
It now appears that the topic of "getting the path to a file within a package" is pretty well-covered. So I think we're in good shape.

For example:
https://r-pkgs.org/data.html#sec-data-system-file
