### ISSUE TITLE
Create a special chunk style for code that does NOT belong in a package

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#778]
Sometimes we have to show and execute some code, in order to make the book render, that should **NOT** appear in real package code.

As it stands, we try to put lots of visible disclaimers in the adjacent prose or in comments, but it's inevitable that people will still copy / paste such snippets and stick them in places where they should not.

It would be nice to use more obvious styling to make such chunks visually distinct.

**Comment by hadley** [comment]
In particular, needed for the setup chunk for the 3 testing chapters.

**Comment by hadley** [comment]
Once we switch to quarto, we might want to use https://quarto.org/docs/authoring/callouts.html

**Comment by hadley** [comment]
I propose we use an important callout for this:

````
::: callout-important
Your test files should not include these `library()` calls.
We also explicitly request testthat edition 3, but in a real package this will be declared in DESCRIPTION.

```{r}
library(testthat)
local_edition(3)
```
:::
````
