### ISSUE TITLE
Conflicting advice for `@importFrom`

### ISSUE THREAD

**Issue by Moohan** [hadley/r-pkgs#780]
The advice on using `@importFrom` in [https://r-pkgs.org/namespace.html#import-r](), seems to conflict with that given in the [https://roxygen2.r-lib.org/articles/namespace.html#imports](Roxygen documentation).

r-pkgs
>If you are using functions repeatedly, you can avoid :: by importing the function with @importFrom pkg fun. This also has a small performance benefit, because :: adds approximately 5 µs to function evaluation time.

roxygen
> Alternatively, though no longer recommended due to its poorer readability, use @importFrom, e.g., @importFrom pgk fun, and call the function(s) without ::.

I think one or both need updating as either I'm misunderstanding in which case the clarity needs improving or one of them is not the correct advice?

**Comment by jennybc** [comment]
The namespace chapter hasn't been revised for the second edition yet.

**Comment by hadley** [comment]
I've deleted the text that I no longer believe in here, and I'll take a quick look at roxygen2 docs too.

**Comment by hadley** [comment]
Looks like roxygen2 is now consistent with this advice.
