### ISSUE TITLE
SUGGESTION: For NEWS.md, maybe refer to pkgdown::build_news() docs?

### ISSUE THREAD

**Issue by HenrikBengtsson** [hadley/r-pkgs#781]
I noticed that `utils::news()` and `pkgdown::build_news()` silently drop information from malformed `NEWS.md` files. In a so-and-so attempt to locate a formal format specification for `NEWS.md` files, I found:

1. https://r-pkgs.org/release.html#news
2. https://pkgdown.r-lib.org/reference/build_news.html

Just a thought, but maybe the former (here), can reference the latter, which seems to be the most formal description this far.

**Comment by jennybc** [comment]
The chapter about package release has not been revised yet for 2e.
