### ISSUE TITLE
suggestions for Chapter 3: System setup

### ISSUE THREAD

**Issue by zkamvar** [hadley/r-pkgs#791]
N.B. I was asked to review Chapters 1-9 by O'Reilly and instructed to leave specific comments here with the understanding of one issue per chapter, ignoring the TODOs:

Overall, this chapter sets folks up for success well. I have some questions and suggestions for the deal with devtools and usethis (which originated in #563)

## Misc

https://github.com/hadley/r-pkgs/blob/31eb7c67788cfc14511668d96615c6ad4be6ea66/Setup.Rmd#L33

suggestion to replace `foo` with `pkg`.

## devtools, usethis, and you

Summed up in https://github.com/hadley/r-pkgs/pull/563#issuecomment-497838205, the point of the chapter is this:

> - Settle once and for all what our recommendations actually are!
> - Develop a clean, only-what-you-need-to-know story about the devtools breakup
> - Concrete instructions on system setup

As someone who has to deal with a tool's long and storied history, I can feel how hard this section is to write in my bones. That being said, I think there could be improvements on the first two points. 

### The weight of history

> After 7 years of development, devtools had grown into a rather unwieldy package, making maintenance difficult. 

I would suggest for the authors to avoid deprecation of the tool the readers will be using throughtout the book as it can be demotivating. It makes sense to set expectations for the reader early, but for someone who is just getting into package development, the history of why is inside baseball (though it does serve well as an example for package scope). My recommendation is to remove the deprecating language and put the history in a footnote for the intrepid and curious readers.

### Dueling narratives

When I read through the section, I was not clear about what its objectives were (until I found https://github.com/hadley/r-pkgs/pull/563#issuecomment-497838205).

As it reads, this section is split into two messages. The first message seems to say "load devtools interactively and use its functions interactively." It then mentions using the functionality from
devtools programmatically, but it's not clear _why_ someone would want to do this since much of the packages are geared for package management and development, which requires the knowlege that this book will teach.

The other message of this section seems to be: "If you have a problem with devtools, figure out what package its coming from and report it there." This can be confusing because it's not always clear where the functions are coming from (as an author of a package that uses the `Depends` field, I know this struggle all too well). 

### Maybe a solution?

The confusion comes in when you read through the narrative, it's organised like so:

````markdown
Historical context

 - useR
 - developR
   - caveat
   - caveat
 - reporting (encompasses useR and developR)

useR example
```
useR mode
```

developR example
```
developR mode
```

usethis: first useR then developR
````

Instead, the message might be more clear if the useR perspective were presented first, explaining reporting, examples, and usethis, followed by the developR perspective:

````markdown
Brief historical context

useR perspective
```
useR example
```
reporting bugs
usethis in relation to devtools (`use_` and `create_` functions)

developR perspective
caveats
```
developR example
```
````

For reporting errors and for the developR perspective, it might be worthwhile to provide an auxillary table of the seven packages that devtools uses from the great uncoupling and what devtools functions they correspond to.

**Comment by hadley** [comment]
I wonder if we might be able to eliminate this chapter all together:

* The setup instruction only really needs to be `install.packages("devtool")` and that plus the `use_devtools()` advice could move into the introduction.
* The introduction also already alludes to the conscious uncoupling, and I agree with you that the current content is probably a bit too much inside baseball, and the vast majority developers don't need to care about it. (We could also mention it in the dependencies section when we discuss why you shouldn't depend on the tidyverse)
* I think we can drop the build toolchain section since we no longer discuss compiled code, and anyway, as the text says RStudio handles it for you most of the time.

@jennybc and I can discuss this when she gets back from vacation.

**Comment by ateucher** [comment]
For my two cents - I think some discussion of the relationship between devtools and it's subsidiaries is warranted, as I think users will hit these questions at some point; though I do agree that the history section is probably unnecessary. I also think that though the chapter could be shortened a bit by removing the build toolchain section, I like it separate from the introduction as it's the first real "how to" chapter. The introduction is more of an overview of what's going to be covered, with some history and context which a user might be tempted to skim over. I also really like the `Personal startup configuration` section.

I think that much of the confusion comes from the "useR"/"developeR" wording - in the context of this book, everyone is a developeR, it's just that sometimes they are using functions interactively to help them write the package, and sometimes they are including functions in their package.

I think that the distinction of using `usethis` etc vs attaching `devtools` could be clarified mostly by dropping the useR/developeR language and focusing on the intended use. E.g., "If you are using the functions interactively to help you build your package, attach `devtools` and call the functions without qualification (e.g., `load_all()`). If you want to use the functions inside the package you are creating, use the namespace of the package where the function is defined along with with the function name (e.g., `usethis::use_template()`)."

I could attempt a PR if any of that makes sense?

**Comment by jennybc** [comment]
Yes @ateucher your summary paragraph resonates a lot with me and I'd be happy if you made a PR to that effect.
