### ISSUE TITLE
suggestions for Chapter 6: The Package Within

### ISSUE THREAD

**Issue by zkamvar** [hadley/r-pkgs#794]
N.B. I was asked to review Chapters 1-9 by O'Reilly and instructed to leave specific comments here with the understanding of one issue per chapter, ignoring the TODOs:

This is an important chapter and the authors mention that mistakes will be made along the way, which puts the reader into the mindset that there will be lessons learned. The main takeaway is that a script has a package embedded, but the mindset for defining functions in a package is fundamentally different than that of defining functions in a script. 

Call me a windmill because I am a huge fan (of this chapter). It really hammers home the message that it is possible to turn a workflow into a package with enough creativity and it finally gets away from the standard "let's create a package that adds two numbers together" sort of constrained tutorials. 

The only issue I have with this is that, ending on a section about side effects, there seems to be no conclusion. Given that this chapter ends this part of the book, it would be helpful to have a final thoughts section (not just a paragraph) at the end that provides some key points for the chapter, otherwise this chapter risks demotivating the reader by ending on a section of gotchas.

**Comment by jennybc** [comment]
> Call me a windmill because I am a huge fan (of this chapter)

Thanks! I'm not particularly satisfied with this chapter, but I do think it's important. Hearing that you (and @ jthomasmock) like it is much-needed encouragement that it's worth holding on to and improving.

I'll incorporate your feedback re: a conclusion when I work on it.
