### ISSUE TITLE
suggestions for Chapter 7: R Code

### ISSUE THREAD

**Issue by zkamvar** [hadley/r-pkgs#795]
N.B. I was asked to review Chapters 1-9 by O'Reilly and instructed to leave specific comments here with the understanding of one issue per chapter, ignoring the TODOs:

There were a couple of sections that could benefit from improvements to clarity.

## Understand when code is executed.

This is an important section. Having two examples that demonstrate the same solution to two different problems is very powerful for readers. My primary suggestions are to clarify that the sub-sections are examples by prefixing "Example:" in the title and to make sure the examples follow similar conventions for exploring the problem and solution space.

### Example: A path returned by `system.file()`

Yes it would be redundant, but mentioning that the `dataTableDependency` object is a _list_ object would really help drive home the point that it is code outside of a function since the term "object" has fluid representation and could mean "function". 

https://github.com/hadley/r-pkgs/blob/31eb7c67788cfc14511668d96615c6ad4be6ea66/Code.Rmd#L172-L190

I would also suggest to include the context of how `dataTableDependency` was used so that you can show the before and after code that would benefit readers offline. This would be in line with the example you give in the next section:

https://github.com/hadley/r-pkgs/blob/31eb7c67788cfc14511668d96615c6ad4be6ea66/Code.Rmd#L207-L223

## Respect the R landscape

https://github.com/hadley/r-pkgs/blob/31eb7c67788cfc14511668d96615c6ad4be6ea66/Code.Rmd#L436-L448

I would suggest to not start with this particular example when you just told readers that you should aways use `.onLoad()` unless you say so.

## CRAN notes

I really love the line numbering for the last example. Please don't change that :)

**Comment by jennybc** [comment]
> I really love the line numbering for the last example. Please don't change that :)

THANK YOU FOR NOTICING!
