### ISSUE TITLE
suggestions for Chapter 8: Package Metadata

### ISSUE THREAD

**Issue by zkamvar** [hadley/r-pkgs#796]
N.B. I was asked to review Chapters 1-9 by O'Reilly and instructed to leave specific comments here with the understanding of one issue per chapter, ignoring the TODOs:

Only one minor suggeston:

https://github.com/hadley/r-pkgs/blob/31eb7c67788cfc14511668d96615c6ad4be6ea66/Metadata.Rmd#L41

It might be nice to include a link to the DCF documentation: https://www.debian.org/doc/debian-policy/ch-controlfields.html

**Comment by hadley** [comment]
R's DESCRIPTION files are very much inspired by DCF, but they don't follow exactly the same spec, so I'd prefer not to link there.
