### ISSUE TITLE
Feedback on Chapter 2: The whole game

### ISSUE THREAD

**Issue by jthomasmock** [hadley/r-pkgs#799]
Generally, is it worth namespacing all of the functions so that people know where they're coming from in this chapter? This is not as big of an issue since it's really `devtools`, `usethis`, `testthat`, as opposed to `tidymodels` or `tidyverse` where there are many packages. However, I know that working with newer learners they can get a bit confused when trying to do small components and may not have all the necessary packages loaded.

### Section 2.4:
-  The RStudio > More > Show Hidden files callout is confusing, the RStudio documentation refers to it as the "Files pane", whereas the file browser makes me thing of "Finder" in Mac OSX. I think it would be worth either explicitly describing it as the Files Pane, the More gear symbol, etc or adding a screenshot.
  - [RStudio docs](https://www.rstudio.com/blog/rstudio-1-2-preview-the-little-things/#:~:text=Show%20hidden%20files,then%20check%20Show%20Hidden%20Files.) referring to show hidden files
  - It's also referred to as "Files pane" later on in the chapter
> What’s in this new directory that is also an R package and, probably, an RStudio Project? Here’s a listing (locally, you can consult your Files pane):
- the `hello.R` file is not mentioned in this chapter and I remember creating my first package years ago and getting into a weird state with `document()` + `pkgdown` when I didn't delete this file early. Overall, I think it's worth mentioning it exists and to delete it.

### Section 2.8:

1. 
> Note that [load_all()](https://devtools.r-lib.org/reference/load_all.html) has made the strsplit1() function available, although it does not exist in the global environment.
> ```r
> [exists](https://rdrr.io/r/base/exists.html)("strsplit1", where = [globalenv](https://rdrr.io/r/base/environment.html)(), inherits = FALSE)
> #> [1] FALSE
> ```
 
- Worth mentioning that RStudio will also throw a warning if you have defined a global function and then `devtools::load_all()`
> R> hello <- function(x){x + 1}
> R> devtools::load_all()
> ```
> ℹ Loading regexcite
> Warning message:
> 
> ── Conflicts ────────────────────── regexcite conflicts ──
> ✖ hello() masks regexcite::hello()
>
> Did you accidentally source a file rather than using `load_all()`?
> Run `rm(list = c("hello"))` to remove the conflicts. 
> ```

2.
In the "RStudio exposes `load_all()` callout, is it with adding _when inside a R package_? This is different when in RMarkdown/Quarto/blog/etc.

### Section 2.10:

There is a great RStudio callout on `ctrl + .` - I checked and this is valid on all platforms. Not sure where it would be best to "live" in the book, but the command palette (ie Cmd + Shift + P) can also execute `devtools` and other RStudio package related commands. Might be worth having an appendix linking out to RStudio/package cheatsheets, RStudio command palette and shortcut documentation. Repeated similar suggestions below. Command palette hits all of the RStudio helpers in build pane and more!

<img width="762" alt="Screen Shot 2022-06-24 at 9 39 45 AM" src="https://user-images.githubusercontent.com/29187501/175558730-60f331e1-0216-4a41-bfcb-f20cc1975c38.png">

### Section 2.12
In the "RStudio exposes document()` callout, is it with adding _when inside a R package_? This is different when in RMarkdown/Quarto/blog/etc. Also same feedback, this is possible with Command Palette > "Document Package"

### Section 2.14

In the "RStudio exposes install callout, is it with adding _when inside a R package_? This is different when in RMarkdown/Quarto/blog/etc. Also same feedback, this is possible with Command Palette > "Install Package"

### Section 2.15

In the "RStudio exposes testthat callout, is it with adding _when inside a R package_? This is different when in RMarkdown/Quarto/blog/etc. Also same feedback, this is possible with Command Palette > "Test"

**Comment by jennybc** [comment]
> Generally, is it worth namespacing all of the functions so that people know where they're coming from in this chapter?

My intention is to only call functions in devtools (or usethis, but devtools Depends on usethis and therefore attaches it). So I think we're OK.

*this comment will evolve as I make it through the items above*
