### ISSUE TITLE
Feedback on Chapter 3: System Setup

### ISSUE THREAD

**Issue by jthomasmock** [hadley/r-pkgs#800]
### Section 3.1

- Consider callout to use at least RStudio 2022.02.3+492 or whatever version is latest when the book is finished. I'm constantly amazed at how out of date folks are with RStudio versions especially with the old semantic versioning system. This would also get folks thinking about calendar-versioning of RStudio, which is a great motivator to the "oh wow I'm 2 years out of date" rather than I'm on v1.2 how old could it be?.

### Section 3.3

- Is it worth having a section on Javascript/python/etc? I see that Other languages (Python) are mentioned in 16.2 but there's minimal guidance.
- The [PyPkgs](https://py-pkgs.org/) book or [JS for R](https://book.javascript-for-r.com/) books may be useful as callouts?

**Comment by jennybc** [comment]
I'm very in tune with the observation re: people having out of date software, including RStudio. It's a constant struggle in workshops! But I feel like we're already urging people to update and to even use the preview version. I don't see an easy way to get into specific RStudio version numbers or version numbering systems without making the content highly perishable. Given that there were 5 years between edition 1 and 2, I don't think I should mention a specific RStudio version number here (the R version mentioned at the start is generated programmatically).

I don't feel educated enough on the Python or JS situation to give people guidance on those languages.

So I've taken these comments into my brain, but just don't see a productive way to implement them at this time.
