### ISSUE TITLE
Feedback on Chapter 7: R Code

### ISSUE THREAD

**Issue by jthomasmock** [hadley/r-pkgs#804]
`tidyeval` is out of scope for this book, but in this chapter you mention `utils.R`, `zzz.R`. I'm following guidance from other devs to add `tidyeval` required anonymous global variables like so in a `myPackageName.R` file:

```
#' @keywords internal
"_PACKAGE"

utils::globalVariables(
  c(
    ".",
    "var", "type", "text", "cmark_rules", "rtf_wrap",
    "Var1", "rtf_escape_unicode", "value", "median", "sd",
    "name", "Mean", "SD", "n_missing", "name", "vals", "x",
    "z_r_group_rows"
  )
)

## usethis namespace: start
## usethis namespace: end
NULL
```

Not sure if that's the "recommended" workflow and if not, skip it, but I think it's worth clarifying in this section what is appropriate for a `myPackageName.R` file, and the use of `utils::globalVariables()`.

### Section 7.1
- Love the Ctrl + . callout, another beat dead horse suggestion to callout the Command Palette and "Go to file" :horse:
- 
### Section 7.5 
- Y'all mention `withr` earlier, but might be nice to call out `withr::with_seed()` explicitly. Either in the `withr` section 7.5.1 or called out to use in place of `set.seed()` in 7.5

> Here is a non-exhaustive list of other functions that should be used with caution:
> 
>[options()](https://rdrr.io/r/base/options.html)
>[par()](https://rdrr.io/r/graphics/par.html)
>[setwd()](https://rdrr.io/r/base/getwd.html)
>[Sys.setenv()](https://rdrr.io/r/base/Sys.setenv.html)
>[Sys.setlocale()](https://rdrr.io/r/base/locales.html)
>[set.seed()](https://rdrr.io/r/base/Random.html) (or anything that changes the state of the random number generator) TODO: maybe tell one or more of the scary stories in https://github.com/hadley/r-pkgs/issues/447

**Comment by jennybc** [comment]
The use of `utils::globalVariables()` is mentioned (briefly) in the chapter on `R CMD check`.

That could be another candidate of content that belongs in a discussion of the package-level help topic, which is being tracked in #531.

> callout the Command Palette and "Go to file" 

I must confess to not being a command palette user (as you know @jthomasmock), but I'll keep an eye out for the right place to mention it. This particular callout is about going from a specific function to the file where it's defined, whereas this tip seems more relevant to when you already know the file you want.
