### ISSUE TITLE
Reconsider which possibilities to cover re: `Remotes`

### ISSUE THREAD

**Issue by jthomasmock** [hadley/r-pkgs#805]
It's worth re-linking to [R Manuals writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file) or [Quarto version](https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html#package-types) if we plan on maintaining that. The metadata is largely duplicated in this chapter, but it provides additional context and is a useful resource.

### Section 8.1.4

Mention [R-Universe](https://ropensci.org/r-universe/) as a `Remotes` option outside of CRAN like Github or Bioconductor.

**Comment by jennybc** [comment]
I have a separate issue now for the general question of links to WRE, so this is now just about what we're going to say re: `Remotes`.

**Comment by jennybc** [comment]
Subsumed by #892
