### ISSUE TITLE
Re-confirm DESCRIPTION custom fields section

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#810]
And document `RoxygenNote` as a historical anomaly.

If you want to stuff arbitrary data, use `Config/`.

**Comment by jennybc** [comment]
The "custom fields" section feels pretty solid to me:

https://r-pkgs.org/Metadata.html#custom-fields

It does show `RoxygenNote` (although it doesn't specifically discuss it as an historical anomaly).

And we describe the use of fields using the `Config/` prefix.

What sort of changes will help? Or can we close this?

**Comment by hadley** [comment]
I'd suggest just discussing `Config/` and removing the `Note` suffix, since that's not really a good place to put arbitrary data.
