### ISSUE TITLE
Discuss internal functions somewhere

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#817]
Text about internal functions removed from `man/` chapter:

> Generally, keywords are not that useful except for @keywords internal. Using the internal keyword removes the function from the package index and disables some of its automated tests. It's common to use @keywords internal for functions that are of interest to other developers extending your package, but not most users.

**Comment by jennybc** [comment]
There is some vague connection to the discussion of `utils.R` here:

https://r-pkgs.org/Code.html#sec-code-organising

Or maybe in this section about exporting:

https://r-pkgs.org/dependencies.html#exports

(Observation: the name of this chapter -- "Dependencies: What does your package need?" -- makes it hard to predict that it has this content re: exporting function.)
