### ISSUE TITLE
`tools::R_user_dir()` / rappdirs

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#818]
It's not a perfect fit, but I think it makes sense to discuss this in the data chapter — i.e. how do you manage data that you want to persist across R sessions.

**Comment by hadley** [comment]
Maybe we should also include a discussion of per session data too? (i.e. using `the <- new.env(parent = emptyenv())`

**Comment by jennybc** [comment]
I like both ideas.

This blog post made a light bulb turn on for me re: how to use an environment for managing package state, so I just want to note it down to re-read when writing this content: https://trestletech.com/2013/04/package-wide-variablescache-in-r-package/.
