### ISSUE TITLE
first edition link is not right

### ISSUE THREAD

**Issue by PursuitOfDataScience** [hadley/r-pkgs#823]
Hi,

"The first edition is available at http://r-pkgs.had.co.nz/" from README that the link doesn't take me to the first edition but rather the second one. Could you please take a look and input the right first edition link? It would be helpful to have both the first edition being isolated from the ongoing second edition. Thanks!

**Comment by jennybc** [comment]
We recently discovered that the first edition is no longer available at that location and probably hasn't been for quite some time. Realistically, we are prioritizing the revision for 2e and are unlikely to resurrect an online version of 1e.

**Comment by dvg-p4** [comment]
You could also link to the Wayback Machine's archive of the first edition, available at:
https://web.archive.org/web/20200108174449/http://r-pkgs.had.co.nz/
It looks like they did a pretty thorough job of crawling the site.
