### ISSUE TITLE
Discuss `All declared Imports should be used.    Namespace in Imports field not imported from`

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#828]
First, check that this isn't developer error. Maybe you really have listed a package in `Imports` that your package does not need! If so, remove it.

---

Sometimes you list a package in `Imports`, but the dependency is not correctly perceived by `R CMD check` and you get this NOTE:

```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘pkgA’
  All declared Imports should be used.
```

Example: you use `pkgA::obj` or `pkgA::fcn()` in the default for a function argument in your package. *Update: maybe describe the way this usually comes up with R6?* 

I've also wanted to list something in `Imports`, even though I made no direct usage of the package, because I wanted to state a minimum version for the indirect dependency. The tidyverse meta-package has this problem on a large scale, since it exists mostly to install a bundle of packages at specific versions.

How do you get rid of the NOTE?

There are a few options. Our recommendation is to put this in some file below `R/`, probably in a file associated with package-wide setup/config/utils:

``` r
fake_function <- function() pkgA::fcn
```

You don't need to call `fake_function()` anywhere. You don't have to actually execute `pkgA::fcn()`. It doesn't even matter if `fcn` is exactly what you use from pkgA. What's important is to access something in pkgA's namespace with `::`.

Unless you have specific reasons to import `fcn()` from pkgA into your NAMESPACE, you don't want to solve this problem with, e.g.,`#' @importFrom pkgA fcn`. If you explicitly import something from pkgA into your NAMESPACE, that causes pkgA to be loaded when your package is loaded. By having a `::` call into pkgA in a phony function, you satisfy `R CMD check`, but pkgA will only be loaded on-demand, i.e. when your user does something that requires loading pkgA.

(above advice developed from some slack discussions over the years, mostly paraphrasing @gaborcsardi)

Also, for lack of a better place to note this, the env var that controls whether `R CMD check` checks for this phenomenon is `_R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_` and historically some of the CRAN machines have this on and others don't. In particular, `--as-cran` actually *turns this check off* (at least in some versions of R https://github.com/r-lib/devtools/issues/2459).

https://github.com/wch/r-source/blob/b6b0a445f44b51507281ef48e032b18606c25ebc/src/library/tools/R/QC.R#L5954-L5956

**Comment by hadley** [comment]
I think we could be a little more assertive:

Our recommendation create a function called `ignore_unused_imports` in your `R/{packagename}-package.R`. It should contain a reference to one function in each package:

```R
ignore_unused_imports <- function() {
  pkgA::fcnA
  pkgB::fcnB
}
```

---

Actually, could we instead do 

```R
ignore_unused_imports <- function() {
  requireNamespace("pkgA")
  requireNamespace("pkgB")
}
```

That has the advantage of not depending on a specific function, which I have a vague sense has caused us trouble in the past.

**Comment by gaborcsardi** [comment]
> Actually, could we instead do

That would be better, but I don't think that it will suppress the NOTE.

**Comment by hadley** [comment]
Ah yeah 😞 It's only [`::`](https://github.com/wch/r-source/blob/b6b0a445f44b51507281ef48e032b18606c25ebc/src/library/tools/R/QC.R#L5714) and [`:::`](https://github.com/wch/r-source/blob/b6b0a445f44b51507281ef48e032b18606c25ebc/src/library/tools/R/QC.R#L5723) that contribute to the list.

**Comment by jennybc** [comment]
I made a concrete demo of this:

> If you explicitly import something from pkgA into your NAMESPACE, that causes pkgA to be loaded when your package is loaded. By having a :: call into pkgA in a phony function, you satisfy R CMD check, but pkgA will only be loaded on-demand, i.e. when your user does something that requires loading pkgA.

I made a toy package with a single function:

```r
foo <- function(x = dplyr::select(data.frame(a = "a"), a)) {
  x[[1]]
}
```

It's the scenario where a dependency (dplyr) is only used in a default argument.

Consider these 4 variations:

* depp1, no `Imports` (baseline)
* depp2, dplyr is listed `Imports`
* depp3, `double_colon` approach: dplyr is listed in `Imports` and below `R/` we define
    ```r    
    fake_function <- function() dplyr::select
    ```
* depp4, `import_from` approach: we import a dplyr function; in NAMESPACE we have
    ```
    importFrom(dplyr,select)
    ````

I ran `R CMD check` for each variant and recorded which packages were loaded at three stages in an `R --vanilla` session, as reported by `sessionInfo()[["loadedOnly"]]`:

* At session start
* After attaching the toy package with `library(deppN)`
* After invoking `foo()`

Yes, both approaches get rid of the NOTE. But importing a function from dplyr causes many packages to be loaded when deppN is attached, whereas the `fake_function <- function() dplyr::select` approach delays this until `deppN::foo()` is invoked.

```
#                 Unused   packages
#                 imports  in
#                 NOTE     loadedOnly
# depp1
#   default arg   no       depp1-1_before_attach.txt (1)
#   uses dplyr             depp1-2_after_attach.txt (1)
#                          depp1-3_after_invocation.txt (21)
#
# depp2           yes      depp2-1_before_attach.txt (1)
#   dplyr in               depp2-2_after_attach.txt (1)
#   Imports                depp2-3_after_invocation.txt (21)
#
# depp3           no       depp3-1_before-attach.txt (1)
#   pkg::colon             depp3-2_after-attach.txt (1)
#                          depp3-3_after-invocation.txt (21)
#
# depp4           no       depp4-1_before-attach.txt (1)
#   importFrom()           depp4-2_after-attach.txt (20)
#                          depp4-3_after-invocation.txt (21)
```

Details with one row per package, which shows:

* compiler is loaded in a fresh vanilla session
* 19 packages are loaded when dplyr is loaded
* 1 package, ellipsis, is loaded when we execute `foo()` (and therefore execute `dplyr::mutate()`)

``` r
dat |>
  mutate(different = depp3 != depp4) |>
  arrange(depp4, pkg) |>
  select(pkg, double_colon = depp3, import_from = depp4) |>
  print(n = Inf)
#> # A tibble: 21 × 3
#> # Groups:   pkg [21]
#>    pkg        double_colon       import_from       
#>    <chr>      <chr>              <chr>             
#>  1 compiler   1_before_attach    1_before_attach   
#>  2 assertthat 3_after_invocation 2_after_attach    
#>  3 cli        3_after_invocation 2_after_attach    
#>  4 DBI        3_after_invocation 2_after_attach    
#>  5 dplyr      3_after_invocation 2_after_attach    
#>  6 fansi      3_after_invocation 2_after_attach    
#>  7 generics   3_after_invocation 2_after_attach    
#>  8 glue       3_after_invocation 2_after_attach    
#>  9 lifecycle  3_after_invocation 2_after_attach    
#> 10 magrittr   3_after_invocation 2_after_attach    
#> 11 pillar     3_after_invocation 2_after_attach    
#> 12 pkgconfig  3_after_invocation 2_after_attach    
#> 13 purrr      3_after_invocation 2_after_attach    
#> 14 R6         3_after_invocation 2_after_attach    
#> 15 rlang      3_after_invocation 2_after_attach    
#> 16 rstudioapi 3_after_invocation 2_after_attach    
#> 17 tibble     3_after_invocation 2_after_attach    
#> 18 tidyselect 3_after_invocation 2_after_attach    
#> 19 utf8       3_after_invocation 2_after_attach    
#> 20 vctrs      3_after_invocation 2_after_attach    
#> 21 ellipsis   3_after_invocation 3_after_invocation
```

**Comment by MichaelChirico** [comment]
Is this not a codetools bug? Has this been reported to r-devel?

**Comment by jennybc** [comment]
No, I have not reported it.

**Comment by hadley** [comment]
@MichaelChirico I don't think this is necessarily a bug in codetools; there are just cases where it's just hard to determine that a package is actually needed. For example, I just needed to use this technique in our internal package that access the data warehouse — it requires dbplyr to work, but only dplyr + DBI code is used in the package. It can also come up when your package requires a package that's only suggested by a dependency (e.g. if you're using `ggplot2::geom_hex()`, you'll need to import hexbin, despite not directly using it).

**Comment by MichaelChirico** [comment]
h/t @moodymudskipper for reporting, there's an associated bugfix:

https://bugs.r-project.org/show_bug.cgi?id=18465

**Comment by dmurdoch** [comment]
I've just been told my patch was merged into R-devel r83774.

**Comment by gaborcsardi** [comment]
Just for the record: the patch fixes this for the case of default values in function arguments referring to packages, but I believe we still need the trick above for build time dependencies in general.

**Comment by gaborcsardi** [comment]
Yeah, typically when packages are only used at install time, i.e. outside of functions. E.g. processx has this:
```
dummy_r6 <- function() R6::R6Class
```
https://github.com/r-lib/processx/blob/e5e4f6a1204a3ff4a3d4b0b055629abb3e3b05ce/R/process.R#L6

I don't think this is easily fixable, though.

**Comment by dmurdoch** [comment]
I see.  I think you linked to the workaround, but the problematic code is here:

    process <- R6::R6Class( .... )

https://github.com/r-lib/processx/blob/e5e4f6a1204a3ff4a3d4b0b055629abb3e3b05ce/R/process.R#L96

Currently the check looks at the objects in the package after parsing and evaluating all the source files.  By that point, there's no more reference to `R6`, there's only the `process` object (an environment, right?) that was produced.  The code is written in such a way that it could look at the source files, parse them itself, and analyze the unevaluated source, but that would presumably be slower.

Something that would slow it down a lot less would be if it examined the contents of `process`.  That would be a pretty simple change.  I don't know if `R6Class()` puts any references to the `R6` package into the objects it creates, but it could do so pretty easily, e.g. something like the `dummy_r6` function.

**Comment by moodymudskipper** [comment]
Another problematic case I encountered is : 

```
widget <- do.call(htmlwidgets::createWidget, c(list(name = "nomnoml", x, package = "nomnoml")))
```

{nomnoml} is called only `through htmlwidgets::createWidget()` in my package and from my comments at the time it seems checks were not green on old ubuntu versions because of that.

**Comment by dmurdoch** [comment]
Yes, the check code isn't going to recognize that you are using `nomnoml` in that code.  I think a workaround like the `dummy_r6` function is the only reasonable soluation there.

**Comment by hadley** [comment]
For what it's worth, I showed Kurt Hornik the `ignore_unused_imports()` approach we recommend in the book and he failed to dislike it, so it's at least mildly approved by CRAN.
