### ISSUE TITLE
Feedback on Licensing: need to consider dependencies

### ISSUE THREAD

**Issue by matdoering** [hadley/r-pkgs#829]
The [licensing section](https://r-pkgs.org/license.html) does not mention that developers should consider the licenses of their dependencies.

Example:
- Alice develops a new R package. All of the non-library code was written by herself, so she wants to place the package under the MIT license.
- Alice's package heavily depends on a GPL3 library
- A user running Alice's library will also run the GPL3 library code, which means that the GPL3 terms should be respected

I also noticed that [tidyverse relicensed all of its packages from GPL to MIT](https://github.com/tidyverse/ggplot2/issues/4236), which indicates that there's also a different interpretation about R package licenses. More generally there seems to be the notion that only the `source code` needs to be considered and not the program that is executed at runtime. That may be true, but I think it's misleading: e.g. if I retrieve the source code for `ggplot2`, the package will tell me it's MIT-licensed. However, if I load the `ggplot2` library and create a plot, this will run GPL-licensed code, e.g. from the packages `gtable` or `nlme`, which is very misleading to me. Based on the license text of `ggplot2`, a company could create a product (not open source) that uses `ggplot2` to generate plots because `ggplot2` has the MIT license. 

For compiled software, certain distinctions make sense, e.g. check the [ffmpeg license](http://ffmpeg.org/legal.html), which will either bei LGPL or GPL depending on how you compile it. But for R packages, there's generally no choice (except for suggested packages): if you load an R library all libraries will be loaded (and used at runtime), so those should be considered when licensing your software, rather than just putting it under MIT without thinking about the dependencies.

The GPL FAQ is also explicitly states that [if you use a GPL library, the whole work must be licensed under GPL](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL). 

So, all in all, I think this warrants a discussion in this section of the book and also more generally, ideally with a clear (legal) recommendation.

**Comment by hadley** [comment]
We don't believe that you need do to consider the license of your dependencies because the package license only covers the material that is in the package. Otherwise all R packages would have to be GPL because R is GPL and your package obviously depends on R.

**Comment by hadley** [comment]
We do have a note to add a few sentences in https://github.com/hadley/r-pkgs/issues/715
