### ISSUE TITLE
Chapter 22: Revdepcheck doesn't exist on CRAN

### ISSUE THREAD

**Issue by lbergelson** [hadley/r-pkgs#839]
The section on [reverse dependency](https://r-pkgs.org/release.html#release-deps) checking has confusing and seemingly incorrect instructions.   It warns that it's under revision, but it's own self correction seems to be inacurate.

It has a crossed out section with a correction, but the correction points to revdepcheck which also doesn't seem to exist.

>To help you do this, ~~devtools provides devtools::revdep_check()~~. This section is slated for revision for the 2nd edition. In the meantime, know that this functionality is now provided by the [revdepcheck](https://r-lib.github.io/revdepcheck/) package.

**Comment by lbergelson** [comment]
It's very possible that I'm doing this wrong, but trying to install it gets this error:

> install.packages("revdepcheck")
Warning message:
package ‘revdepcheck’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by lbergelson** [comment]
It appears that it is intentionally not on CRAN but the installation instructions in the readme are confusing.

For anyone who finds this in the future this will install it:

```
devtools::install_github('r-lib/revdepcheck')
```

**Comment by hanneoberman** [comment]
Could a footnote be added to the checklist item to tell the impatient readers that `revdepcheck` is not on CRAN? 
https://github.com/hadley/r-pkgs/blob/6c48a2e9af097302ab1e990992699bc7e5012ea0/release.Rmd#L298
Now, this is explained a couple of sentences ahead in the text, but not visible at the first appearance of the code.
https://github.com/hadley/r-pkgs/blob/6c48a2e9af097302ab1e990992699bc7e5012ea0/release.Rmd#L319
