### ISSUE TITLE
Chapter 6 feedback 

### ISSUE THREAD

**Issue by malcolmbarrett** [hadley/r-pkgs#840]
This link doesn't work: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/Package-within.Rmd#L235

---

I get substantially different R CMD Check results from https://github.com/malcolmbarrett/delta

https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/Package-within.Rmd#L349-L357

---

I think it's worth mentioning, if in passing, that you'd need to import withr with this approach: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/Package-within.Rmd#L671-L679

**Comment by jennybc** [comment]
The link to design.tidyverse.org appears to be working now.

I am about to go over all the mechanics re: the various versions and that will give me the chance to make sure the `R CMD check` results shown for delta are up-to-date.
