### ISSUE TITLE
 Chapter 8 feedback ("Data")

### ISSUE THREAD

**Issue by malcolmbarrett** [hadley/r-pkgs#842]
In general, this chapter doesn't feel as far along as the others so far.

---

I think this should include `use_data()` or at least some more details on the format so people don't just OK GOT IT and plop something weird in `data/`: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/data.Rmd#L16-L17

---

I don't think this is totally clear: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/data.Rmd#L20

Maybe: This is the best place to put data that your functions need but your users don't?

---

This needs to be clarified in terms of its relationship to `data-raw` and `use_data_raw()`: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/data.Rmd#L22

Probably also merits a link to the `inst/` section in the next chapter.

Also, this is just a convention, right? Since it's in `inst`, it can really be anything. I think it should be at least explicitly called out as a convention. Personally, I teach this as "you can put it in `inst/`" and a supplemental fact about that is there's this convention `extdata`. (I don't think it's a very useful convention if you can't tell. It's not like I go spelunking into `extdata` of some package hoping something is there.)

---
Re: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/data.Rmd#L50-L55

Switch to lobstr?

---

Re: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/data.Rmd#L47

"You can see that memory usage doesn’t change until you inspect the flights dataset stored inside the package." -> "You can see that memory usage doesn’t change *much* until you inspect the flights dataset stored inside the package."

**Comment by jennybc** [comment]
> In general, this chapter doesn't feel as far along as the others so far.

This chapter had not been revised yet, but it's happening now and the revised version should address the points raised above.
