### ISSUE TITLE
Chapter 9 feedback ("Other components")

### ISSUE THREAD

**Issue by malcolmbarrett** [hadley/r-pkgs#843]
This chapter also needs a facelift still

---

I don't think this is true of `inst/`. Rar*er*, certainly, than other key directories, but still common enough: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/misc.Rmd#L11

---

Worth mentioning `template`? I find it to be a high-yield topic when discussing internal packages in particular

https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/misc.Rmd#L36

---

Mention `use_citation()` somewhere in this section: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/misc.Rmd#L56

--- 

I think c and c++ deserve specific mentions here, too, since the same advice does not apply: https://github.com/hadley/r-pkgs/blob/37aad0092f491a49800cb15aa6e7ff837621cb6f/misc.Rmd#L100

**Comment by jennybc** [comment]
I just updated this chapter and, though I forgot to find and read this before/during that, I think I ended up addressing these concerns.
