### ISSUE TITLE
Ch 3.2.1 Personal startup configuration usethis.protocol  = "ssh"

### ISSUE THREAD

**Issue by shannonpileggi** [hadley/r-pkgs#854]
Hi! We are reading 2e in book club at work and we are really enjoying it! Thank you for all of you efforts in this wonderful book!

In Ch 3.2.1 Personal startup configuration, the [`.Rprofile` options shown include `usethis.protocol  = "ssh"`](https://github.com/hadley/r-pkgs/blob/807369d7a4e72b7fd1f7c55131bfbd0620107d35/Setup.Rmd#L102).  It seems like there have been a lot of amazing advances in `usethis` over recent years that make protocols painless, and we were wondering if this option should remain or be removed.

**Comment by jennybc** [comment]
No, I would be prefer to drop setting that option (`usethis.protocol`) from the example. A PR would be welcome!

It looks like usethis's vignette about setup could also use a similar change. PR welcome there too.

https://usethis.r-lib.org/articles/usethis-setup.html#store-default-values-for-description-fields-and-other-preferences
