### ISSUE TITLE
Organise project as an R package 

### ISSUE THREAD

**Issue by AmelZulji** [hadley/r-pkgs#859]
Hi folks, 

I would like to try organising a DS project as an R package. I have checked suggestion mentioned here:  

> It’s even possible to use packages to structure your data analyses (e.g., Marwick, Boettiger, and Mullen ([2018a](https://r-pkgs.org/references.html#ref-marwick2018-tas)) or Marwick, Boettiger, and Mullen ([2018b](https://r-pkgs.org/references.html#ref-marwick2018-peerj))), although we won’t delve deeply into that use case here.

However, my data  (raw and final) are way bigger (~50 GB in total). Do you have any recommendation for that particular scenario? 

Thank you and kind regards,
Amel

**Comment by jennybc** [comment]
I'm afraid that our expertise is heavily weighted towards conventional R packages. I think you'll get much more informed answers if you open a thread in rOpenSci's forum (https://discuss.ropensci.org) or in  ~RStudio~ Posit Community (https://community.rstudio.com).

**Comment by jennybc** [comment]
``
