### ISSUE TITLE
Depends, Imports, and Suggests in the DESCRIPTION file

### ISSUE THREAD

**Issue by aaelony** [hadley/r-pkgs#863]
When you know the package you are authoring will have a dependency, the next question is whether this dependency should be declared as `Depends`, `Imports`, or `Suggests` in the `DESCRIPTION` file.  It would be very useful to include such a discussion, along with ramifications of each.  I think this information exists, but it could be improved as it is scattered throughout the book.  Feel free to close this issue if you disagree.

**Comment by jennybc** [comment]
Covered in https://r-pkgs.org/dependencies.html
