### ISSUE TITLE
Bad interaction between a footnote and the main content

### ISSUE THREAD

**Issue by jennybc** [hadley/r-pkgs#872]
Currently losing a battle between the footnote about `RoxygenNote` in `DESCRIPTION` and the attempt to show `.Rd` content:

https://github.com/hadley/r-pkgs/blob/f1af948c45659c9bc5b9cccf72c19ade1b58d1ab/man.Rmd#L105

https://github.com/hadley/r-pkgs/blob/f1af948c45659c9bc5b9cccf72c19ade1b58d1ab/man.Rmd#L111-L133

RStudio keeps mangling the latter and putting it in the footnote.

It's happening in this section: https://r-pkgs.org/man.html#sec-man-workflow

**Comment by hadley** [comment]
Also worth noting that O'Reilly's footnotes don't really handle rich text, so you might want to reword to a single sentence
