### ISSUE TITLE
R code chapter: no nested directories in R/

### ISSUE THREAD

**Issue by nick-youngblut** [hadley/r-pkgs#876]
This applies to the `R code` chapter:

For those transitioning from python to R package development, it would be helpful to point out that the `R` directory CANNOT contain subdirectories of code, but MUST contain all `*.R` source files in the `R` directory. Otherwise, functions such as `devtools::load_all()` will not load all of the package code, since it won't recursively search the subdirectories in `R`. 

Maybe pointing to a package such as https://github.com/tidyverse/ggplot2/tree/main/R, will demonstrate how one must group `*.R` packages by file name prefixes instead of actually creating subdirectories to hold files of associated functions, as a developer would generally do for a python package (e.g., https://github.com/numpy/numpy/tree/main/numpy or https://github.com/pandas-dev/pandas/tree/main/pandas).

**Comment by jennybc** [comment]
https://github.com/hadley/r-pkgs/blob/55e8e4ca51d567d37a2e97af8f456a0ea118b628/code.Rmd#L20-L21

We have a footnote with this exact information.
