### ISSUE TITLE
Why isn't Jenny's name on the cover of R Packages?

### ISSUE THREAD

**Issue by InfiniteCuriosity** [hadley/r-pkgs#887]
If Jenny is a co-author, why is only Hadley's name on the cover?

The author section:
>AUTHOR
Hadley Wickham and Jenny Bryan
source: https://r-pkgs.org

The cover of the book:
![Screen Shot 2022-11-20 at 8 30 13 AM](https://user-images.githubusercontent.com/21028719/202907984-d75dd66c-4f72-4499-886f-0ebc6624e94c.png)
source: https://r-pkgs.org

**Comment by jennybc** [comment]
That's the cover of the first edition (I'm staring at a hard copy now) and there is not yet an equivalent cover or image for the second edition.
