### ISSUE TITLE
An example package using roxygen comments including almost all the tags, esp. the S4 related.

### ISSUE THREAD

**Issue by zhilongjia** [hadley/r-pkgs#89]
This is not a bug. 
It's a powerful documenting system. 

The document related the S4 object (http://r-pkgs.had.co.nz/man.html) is kind of unclear for me. For example, I just do not know how to comment the S4 generics and $4 Methods? Also  the /item tags is not appear in this document. So, could you recommend an package using the roxygen comments to me or R users? Thank you.

**Comment by hadley** [comment]
Overall, the roxygen2 chapter needs more examples

**Comment by hadley** [comment]
I think this is now superseded by the new roxygen2 website: http://roxygen2.r-lib.org/
