### ISSUE TITLE
A way to possibly clear up some directions in chapter 2

### ISSUE THREAD

**Issue by InfiniteCuriosity** [hadley/r-pkgs#896]
I'm working my way through R Packages, currently in chapter 2. I was **finally** able to get the most basic steps to work because I had to fill in a number of important steps that were missing in the online text. The most basic issue I experienced is that the code to verify the function was not in the Global Environment only worked when I wrote it in the Console. Period. Nothing else worked, and I tried a lot of options.

Once I entered create_package() (in section 2.5), I tried to proceed in the new environment. Each time I got to the code for exists("strsplit1", where = globalenv(), inherits = FALSE), RStudio kept returning TRUE, and it was in the global environment. It wasn't until I tried the code in the Console that everything ran, and the code to test if it exists in the global environment returned FALSE. 

That solution was extremely not-obvious to me, and took quite a while to figure out. A simple screenshot such as the attached image would make this much clearer, in addition to the directions where the code needs to be entered in RStudio.

It was helpful that the text said it should return false, but the steps provided if it returned TRUE did not solve the problem, as my many attempts showed me.  I was entering code in the wrote area, and had to hunt to find where it should be entered.

It's possible I still misunderstand the directions, but please add screenshots and clear directions where the code is to be entered. This should be an easy fix (and much shorter than this note!)

![Screen Shot 2022-12-12 at 12 43 02 PM](https://user-images.githubusercontent.com/21028719/207128627-dde83437-fdfa-4da0-bf89-f0d59d6474d2.png)

**Comment by jennybc** [comment]
> The most basic issue I experienced is that the code to verify the function was not in the Global Environment only worked when I wrote it in the Console.

I don't understand where else one could execute this code other than the Console?

Your screenshot shows you defining `strsplit1()` in the global environment, which is exactly what we *don't* want to do when test driving package code. And that explains why, yes, `strsplit()` is reported as existing in the global environment. Instead, we use `load_all()` to make package available for interactive use. So I think you're just going through the learning process, but there's nothing to change here.
