### ISSUE TITLE
Possible clarification of steps in testing

### ISSUE THREAD

**Issue by InfiniteCuriosity** [hadley/r-pkgs#899]
On this page, [https://r-pkgs.org/whole-game.html](https://r-pkgs.org/whole-game.html), the text says, "Run this test interactively, as you will when you write your own." I have no idea how to do that at this point. Would you consider re-writing how to run a test interactively as a sequence of steps? For example:

Run this test interactively in the Console of your active R session:
1. library(testthat)
2. load_all()
3. test()

I find a sequence of steps like that to be clearer to me than a body of text.

**Comment by jennybc** [comment]
The intent is for the reader to run the test in whatever way they normally run a bit of R code. For example, in RStudio, Ctrl/Cmd + Enter. I don't think more words here would be a net gain for clarity.
