### ISSUE TITLE
Cite the source for the quote in 5.2.2 - and this cite is really good :)

### ISSUE THREAD

**Issue by InfiniteCuriosity** [hadley/r-pkgs#903]
5.2.2 quotes Phil Karlton, "“There are only two hard things in Computer Science: cache invalidation and naming things.” I don't see a cite for that quote in the book, so I looked it up. You might want to consider this cite for the quote in the book:

[https://skeptics.stackexchange.com/questions/19836/has-phil-karlton-ever-said-there-are-only-two-hard-things-in-computer-science](https://skeptics.stackexchange.com/questions/19836/has-phil-karlton-ever-said-there-are-only-two-hard-things-in-computer-science)

"As his only son, and colleague with him at Netscape from 95-97, I can attest that my dad did indeed throw that quote around, on more than one occasion. I'm fairly confident that he originated it (he was fond of coming up with clever quippets), though I haven't been able to figure out how it disseminated so widely over the past couple of decades. I'll keep looking around in old web archives and mails to see if I can dig something up."

Reference from David Karlton's personal blog at karlton.org: https://www.karlton.org/2017/12/naming-things-hard/

**Comment by jennybc** [comment]
I'm OK with just crediting the author.
