### ISSUE TITLE
Possible capitalization error in 10.4

### ISSUE THREAD

**Issue by InfiniteCuriosity** [hadley/r-pkgs#907]
Section 10.4 includes this text: "Here’s an example of such usage (note the auto-generated URI):" Would it be more accurate if the last letter was L and not I, so it's an "auto-generated URL"? Or should it be kept as "auto-generated URI"?

Source: [https://r-pkgs.org/description.html](https://r-pkgs.org/description.html)

**Comment by jennybc** [comment]
I am using URI intentionally here, following the lead of the ORCID docs.

https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

> The ORCID iD is an https **URI** with a 16-digit number that is compatible with the ISO Standard ([ISO 27729](https://www.iso.org/standard/44292.html)), also known as the International Standard Name Identifier (ISNI), e.g. https://orcid.org/0000-0001-2345-6789
