### ISSUE TITLE
Chapter 8 : how to document raw data ?

### ISSUE THREAD

**Issue by GillesSanMartin** [hadley/r-pkgs#916]
It remains unclear to me how we should document raw files that are only stored in inst/extdata/.
Should we necessarily create .RData versions of these raw files in the /data directory ?  (then a simple sentence in section 8.4 and a cross reference to 8.2.2 could clarify this point.)
Or is there a way to avoid this duplication if all we want is raw files ?

**Comment by jennybc** [comment]
To bring more clarity, I think one needs to ask: why are these files in `inst/extdata/`? The answer to that suggests whether and how to document.

A typical use of such files is to provide official example files that get used in function examples, vignettes, etc. In which case, I typically create an accessor function. Which makes the accessor function the obvious place to document these files.

https://readr.tidyverse.org/reference/readr_example.html

https://readxl.tidyverse.org/reference/readxl_example.html

https://googledrive.tidyverse.org/reference/drive_examples.html

I guess I think of this as sort of a self-resolving issue. If users need to know about these files, then presumably there is a user-facing function that exposes or uses them. And that's where they get documented.

If users *don't* need to know about these files, then they don't need to be documented.

Does that clarify things?
