### ISSUE TITLE
Additional notes on chapter 6 

### ISSUE THREAD

**Issue by guru809** [hadley/r-pkgs#925]
![image](https://user-images.githubusercontent.com/10312456/212148983-54be5fb0-28ea-48ae-84b2-75f669fa1622.png)
The first note regarding posixct is repeated at 5

**Comment by jennybc** [comment]
Yeah this is (sort of) intentional and known. So far, I haven't figured out how or if I can point to the same text twice. So I'm tolerating this duplication for now.
