### ISSUE TITLE
Replace "Twitter" mentions with "social media"

### ISSUE THREAD

**Issue by mccarthy-m-g** [hadley/r-pkgs#928]
For example, instead of this:

https://github.com/hadley/r-pkgs/blob/f44475e99be2a13c1838e96e2e42829343e5e79d/release.Rmd#L313

You could write:

"If you use social media, post about it with the #RStats hashtag."

**Comment by jennybc** [comment]
I seem to have already changed this to include Mastodon, etc. Thanks.
