### ISSUE TITLE
Do we need more re: build toolchain for compiled code for linux users?

### ISSUE THREAD

**Issue by ateucher** [hadley/r-pkgs#937]
This was removed in #936, but we should probably re-add it. This is the original text:

```
## R build toolchain {#setup-tools}

To be fully capable of building R packages from source, you'll also need a compiler and a few other command line tools.
This may not be strictly necessary until you want to build packages containing C or C++ code.
Especially if you are using RStudio, you can set this aside for now.
The IDE will alert you and provide support once you try to do something that requires you to setup your development environment.
Read on for advice on doing this yourself.

### Windows

On Windows the collection of tools needed for building packages from source is called Rtools.

Rtools is NOT an R package.
It is NOT installed with `install.packages()`.
Instead, download it from <https://cran.r-project.org/bin/windows/Rtools/> and run the installer.

During the Rtools installation you may see a window asking you to "Select Additional Tasks".

-   Do *not* select the box for "Edit the system PATH". devtools and RStudio should put Rtools on the `PATH` automatically when it is needed.
-   Do select the box for "Save version information to registry". It should be selected by default.

### macOS

You need to install the Xcode command line tools, which requires that you [register as an Apple developer](https://developer.apple.com/programs/register/) (don't worry, it's free).

Then, in the shell, do:


    ```shell
    xcode-select --install
    ```

Alternatively, you can install the current release of full [Xcode from the Mac App Store](https://itunes.apple.com/ca/app/xcode/id497799835?mt=12).
This includes a very great deal that you do not need, but it offers the advantage of App Store convenience.

### Linux

Make sure you've installed not only R, but also the R development tools.
For example, on Ubuntu (and Debian) you need to install the `r-base-dev` package.

```

**Comment by jennybc** [comment]
My hunch is that we cannot completely remove this and purely coast on the IDE doing whatever is necessary. But we want to keep this section quite lean.

**Comment by ateucher** [comment]
That makes sense, especially if some people aren't using RStudio. I think it's quite lean already, but I'll see if I can trim it down any more (though I think it's quite good as is)!

**Comment by jennybc** [comment]
Yeah I don't actually understand the argument for removal.

**Comment by ateucher** [comment]
I also don't really see where I can trim much content here... I'd propose just putting it back in as is.

**Comment by ateucher** [comment]
We decided to keep this content in #936. We need to decide if we should augment the linux section.

**Comment by ateucher** [comment]
I'm not really sure we need too much more on Linux here. `r-base-dev` installs all the tools required for building packages with C/C++/Fortran, as far as I can tell. We could add a line with `sudo apt install r-base-dev` for Debian and Ubuntu users (surely the vast majority)?
