### ISSUE TITLE
Installed files (section 9.3)- besides CITATION and extdata, are there conventions or recommendations for when including reports, apps and APIs in an R package?

### ISSUE THREAD

**Issue by mskyttner** [hadley/r-pkgs#958]
An R package can provide [misc files in inst](https://r-pkgs.org/misc.html#sec-misc-inst) such as APIs, apps and reports. Issue #655  mentions some such types of assets. What recommendations and conventions apply when adding these kinds of features to an R package?

a) a Plumber API - it seems `inst/plumber` could be the convention here, see the example at https://github.com/sol-eng/plumbpkg
b) a Shiny app - it seems `inst/shiny` could be the convention here, see an example at https://gist.github.com/jbryer/fc8834279189196ead710e89b56d7f88 and there is also [golem](https://engineering-shiny.org/golem.html) which packages a Shiny app as an R package.
c) an Rmarkdown report - it seems `inst/rmarkdown` (or maybe inst/rmd) could be the convention here, see examples at https://github.com/rstudio/rticles/tree/main/inst/rmarkdown and https://stackoverflow.com/questions/30377213/how-to-include-rmarkdown-file-in-r-package and the gotchas if rendering an Rmarkdown report from a Shiny app in the R package that are mentioned at https://mastering-shiny.org/action-transfer.html#downloading-reports

Could/should those locations under "inst" be considered to be conventions for those kinds of assets?

d) a quarto document, ie a `.qmd` file or template? Another newer type of report is a quarto document, where an R package may want to bundle such a report (just like an .Rmd document) and offer a function to render it, possibly with some parameter(s) and store the output in a specified location, see https://github.com/quarto-dev/quarto-r/issues/54

What is the recommended way to include a quarto document in an R package?

**Comment by jennybc** [comment]
These are all interesting questions, but I doubt we're going to take a position on these in the second edition which is in "necessary changes only" mode. Once we get it into the formal publication process, we can re-open our minds to matters like this, as the online version of the book is an evolving document.

**Comment by jennybc** [comment]
Psychologically, it helps me to close issues that won't get attention in the current print edition. Feel free to bring this up again in the future, once the second edition push is over. I can also imagine many of these matters re-appearing organically.
