### ISSUE TITLE
Add explanation about Github workflow permissions in chapter 20

### ISSUE THREAD

**Issue by matanhakim** [hadley/r-pkgs#977]
Section 20.2 declares:

> After successful execution of use_pkgdown_github_pages(), you should be able to visit your new site at the URL displayed in the output above.

Nevertheless, there is one more step needed for the website to be properly published.
One should go to its Github repo, and then:

1. Settings
2. Actions
3. General
4. Scroll down to "Workflow permissions"
5. Check "Read and write permissions"

Without this, my Github Actions kept failing.
Only after looking my error online I found this solution, and now it works.
I think this should be added to save valuable time for first-time package developers like myself.

Thanks again for the book!
It facilitated my first package, [rtlr](https://github.com/matanhakim/rtlr) - you're welcome to check it out!

**Comment by jennybc** [comment]
Apparently this is a somewhat new phenomenon, since February perhaps? So, yeah we'll do something about it here and in usethis, where it's already being tracked. https://github.com/r-lib/usethis/issues/1813

Glad the book has been useful! Thanks for the thoughtful issues and PRs.
