### ISSUE TITLE
Can't move past use_git()

### ISSUE THREAD

**Issue by mariacuellar** [hadley/r-pkgs#983]
[use_git](https://usethis.r-lib.org/reference/use_git.html)()
I did this step (use_git()) and it's stuck at "Selection: 2 ✔ Adding files". It won't progress or make the new files in gitignore. What can I do? Thanks!

**Comment by jennybc** [comment]
This issue doesn't appear to be, e.g., a typo or error in the book, but is rather a setup/usage issue on your end, so it's more suitable for [Posit Community](https://community.rstudio.com).
