### ISSUE TITLE
use_github_action() behaves differently than described

### ISSUE THREAD

**Issue by EllaKaye** [hadley/r-pkgs#987]
Hello. In section 21.2.2 it states that `use_github_action()`with no argument prompts a menu of options. I just tried that and got an error message instead:

``` r
usethis::use_github_action()
#> Error in usethis::use_github_action(): argument "name" is missing, with no default
```

This is `usethis` v2.1.6.

<sup>Created on 2023-05-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
We are describing behaviour in dev usethis, which will soon be released.

**Comment by EllaKaye** [comment]
Oh cool! That's a really nice new feature. And now I'm excited to see what else this upcoming usethis release has in store 😀
