### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [hadley/r-pkgs#997]
Cartesian
downlit
every time
minimum
particularly

```
$ grep -nr cartesian r-pkgs
r-pkgs/dependencies-in-practice.Rmd:407:#'   # Plot it in cartesian coordinates
$ grep -nr downlig r-pkgs
r-pkgs/whole-game.Rmd:712:<!-- TODO: I have no idea why I have to disable crayon here, but if I don't, I guess raw ANSI escapes. Other chunks seem to work fine with downlig. It would also be nice to not see evidence of progress reporting, but the previous approach to turning that off keeps this chunk from showing any output at all :( The previous approach was `R.options = list(testthat.default_reporter = testthat::ProgressReporter$new(update_interval = Inf))`. -->
$ grep -nr everytime r-pkgs
r-pkgs/package-within.Rmd:548:# I don't want the instant to change everytime we render the book, so NO:
$ grep -nr minium r-pkgs
r-pkgs/description.Rmd:295:### Minimum versions {#sec-description-imports-suggests-minium-version}
r-pkgs/lifecycle.Rmd:132:R offers this support for working with package versions, because it's necessary, for example, to determine whether package dependencies are satisfied (@sec-description-imports-suggests-minium-version).
$ grep -nr particulary r-pkgs
r-pkgs/code.Rmd:48:  Comments = "Defines exactly one function, `uncount()`, that's not particulary large, but doesn't fit naturally into any other `.R` file"
$ 
```

innocuous but could standardise repo wide the spelling here; `synced` seems the more typical in coding  

```
$ grep -nr synched r-pkgs
r-pkgs/LICENSE:81:     synched in timed relation with a moving image.
$ grep -nr synched r-pkgs | wc -l
1
$ grep -nr synced r-pkgs | wc -l
2
$ 
```

_July 8, 2023_

The LICENSE used is from Creative Commons, accordingly it shouldn't be modified.

<hr>

the string `"breakingness"` is obscure

possibly rewrite the relevant paragraph

```
$ grep -nr breakingness r-pkgs
r-pkgs/lifecycle.Rmd:22:In @sec-lifecycle-breaking-change-definition, we explore how to determine whether something is a breaking change or, more realistically, to gauge where it lies on a spectrum of "breakingness".
$ 
```

**Comment by neshvig10** [comment]
I have fixed the typos , PTAL

**Comment by spaette** [comment]
> PTAL

The repo files in the `grep` output have no newer commits than thirty days ago.

**Comment by neshvig10** [comment]
> > PTAL
> 
> The repo files in the `grep` output have no newer commits than thirty days ago.

I just fixed the typos , 
What other changes to be made ?

**Comment by spaette** [comment]
thought you meant a merge was made

**Comment by neshvig10** [comment]
> thought you meant a merge was made

No 😅

**Comment by spaette** [comment]
your PRs are not resource sparing in terms of reviews and workflows

suggest you close all but `#1006` which was a repo wide optional spelling standardisation

if you oblige then the actual typo fixes I will include in my own submitted single pull request

**Comment by jennybc** [comment]
@neshvig10 and @spaette Are you participating in some sort of organized activity around making PRs into open source projects? While I do appreciate the spell-checking, yes, this is starting to describe how it feels on the receiving end:

> PRs are not resource sparing in terms of reviews and workflows

Sometimes the typo fix is in a very internal comment or is a typo in actual code we're including. So the PRs are really flirting with the border between being helpful and a nuisance.

**Comment by spaette** [comment]
> suggest you close all but `#1006` which was a repo wide optional spelling standardisation
> 
> if you oblige then the actual typo fixes I will include in my own submitted single pull request

@jennybc that simply represented expediency on my part not a semblance of `some sort of organized activity`

Presuming one wanted to convert first character of  `cartesian` to a capital letter these changes are obvious.

Cartesian
downlit
every time
minimum
particularly

Standardising spelling was incidental and @hadley had chipped in on the neologism which should be kept.

> my own submitted single pull request

https://github.com/hadley/r-pkgs/pull/1007

I can add spelling standardisation to that prior to merge or just leave it as is, or separately `#1006` could be merged.

**Comment by neshvig10** [comment]
I'm actually new to open source and mistakenly I made multiple PRs

**Comment by neshvig10** [comment]
Can you please merge my PRs , that fixes all typos

**Comment by spaette** [comment]
> new to open source

Speculation but owing to the naming of your fork's branches it crossed my mind that online editing was used.

If that speculation has a factual basis that is in contrast to the command-line clone, patch, add, commit, and push.

> mistakenly

Occasionally one may encounter a request from a repo Maintainer to break up a single PR into multiple PRs.

> fixes all typos

A potential concern might be checks being run where the string `minium` is changed in `#999` and in `#1000`. 

<hr>

This Issue has gone in the direction of occupying Author and Collaborator time which was not my intention in opening.

> I can add spelling standardisation to that prior to merge or just leave it as is, or separately `#1006` could be merged.

IMHO, the foregoing is the simple solution.

**Comment by spaette** [comment]
> The LICENSE used is from Creative Commons, accordingly it shouldn't be modified.

The linked to PR can now have a Maintainer approve the workflow.
